package snd.komelia.ui.strings

val EnStrings = AppStrings(
    filters = FilterStrings(
        anyValue = "Any",

        filterTagsSearch = "Search tags",
        filterTagsReset = "Reset",
        filterTagsGenreLabel = "Genre",
        filterTagsTagsLabel = "Tags",
        filterTagsShowMore = "Show more",
        filterTagsShowLess = "Show less",
        includeIfAllMatch = "If all match",
        includeIfAnyMatch = "If any match",
        excludeIfAllMatch = "If all match",
        excludeIfAnyMatch = "If any match",
    ),
    seriesFilter = SeriesFilterStrings(
        resetFilters = "Reset filters",
        hideFilters = "Hide filters",
        anyValue = "Any",
        search = "Search",

        sort = "Sort by",
        sortRandom = "Random",
        sortRatingDesc = "Your rating",
        sortTitleAsc = "Title Ascending",
        sortTitleDesc = "Title Descending",
        sortDateAddedAsc = "Oldest Added",
        sortDateAddedDesc = "Recently Added",
        sortReleaseDateAsc = "Oldest Release Date",
        sortReleaseDateDesc = "Latest Release Date",
        sortUpdatedAsc = "Oldest Update",
        sortUpdatedDesc = "Latest Update",
        sortFolderNameAsc = "Folder Name Ascending",
        sortFolderNameDesc = "Folder Name Descending",
        sortBooksCountAsc = "Least Books",
        sortBooksCountDesc = "Most Books",

        filterTagsLabel = "Filter tags",
        readStatus = "Read status",
        readStatusUnread = "Unread",
        readStatusInProgress = "In progress",
        readStatusRead = "Read",

        publicationStatus = "Publication status",
        pubStatusEnded = "Ended",
        pubStatusOngoing = "Ongoing",
        pubStatusAbandoned = "Abandoned",
        pubStatusHiatus = "Hiatus",

        complete = "Complete",
        oneshot = "Oneshot",
        authors = "Authors",
        publisher = "Publisher",
        language = "Language",
        releaseDate = "Release date",
        ageRating = "Age rating"
    ),
    booksFilter = BookFilterStrings(
        sort = "Sort order",
        sortNumberAsc = "Ascending",
        sortNumberDesc = "Descending",

        sortFileNameAsc = "Filename ascending",
        sortFileNameDesc = "Filename descending",
        sortReleaseDateAsc = "Latest release date",
        sortReleaseDateDesc = "Oldest release date",

        readStatus = "Read status",
        readStatusUnread = "Unread",
        readStatusInProgress = "In progress",
        readStatusRead = "Read",

        authors = "Authors",
        tags = "Filter Tags",
    ),
    seriesView = SeriesViewStrings(
        statusEnded = "Ended",
        statusOngoing = "Ongoing",
        statusAbandoned = "Abandoned",
        statusHiatus = "Hiatus",
        readingDirectionLeftToRight = "Left to right",
        readingDirectionRightToLeft = "Right to left",
        readingDirectionVertical = "Vertical",
        readingDirectionWebtoon = "Webtoon",
    ),
    seriesEdit = SeriesEditStrings(
        title = "Title",
        sortTitle = "Sort title",
        summary = "Summary",
        language = "Language",

        status = "Status",
        statusEnded = "Ended",
        statusOngoing = "Ongoing",
        statusAbandoned = "Abandoned",
        statusHiatus = "Hiatus",

        readingDirection = "Reading Direction",
        readingDirectionLeftToRight = "Left to right",
        readingDirectionRightToLeft = "Right to left",
        readingDirectionVertical = "Vertical",
        readingDirectionWebtoon = "Webtoon",
        publisher = "Publisher",
        ageRating = "Age rating",
        totalBookCount = "Total book count"
    ),
    bookEdit = BookEditStrings(
        title = "Title",
        number = "Number",
        sortNumber = "Sort Number",
        summary = "Summary",
        releaseDate = "Release date",
        isbn = "ISBN"
    ),
    libraryEdit = LibraryEditStrings(
        emptyTrashAfterScan = "Empty trash automatically after every scan",
        scanForceModifiedTime = "Force directory modified time",
        scanOnStartup = "Scan on startup",
        oneshotsDirectory = "One-Shots directory",
        excludeDirectories = "Directory exclusions",

        scanInterval = "Scan interval",
        scanIntervalDisabled = "Disabled",
        scanIntervalHourly = "Hourly",
        scanIntervalEvery6H = "Every 6 hours",
        scanIntervalEvery12H = "Every 12 hours",
        scanIntervalDaily = "Daily",
        scanIntervalWeekly = "Weekly",

        hashFiles = "Compute hash for files",
        hashPages = "Compute hash for pages",
        analyzeDimensions = "Analyze pages dimensions",
        repairExtensions = "Automatically repair incorrect file extensions",
        convertToCbz = "Automatically convert to CBZ",
        seriesCover = "Series cover",
        coverFirst = "First",
        coverFirstUnreadOrFirst = "First unread else first",
        coverFirstUnreadOrLast = "First unread else last",
        coverLast = "Last"
    ),
    userEdit = UserEditStrings(
        contentRestrictions = "Content restrictions",
        age = "Age",
        labelsAllow = "Allow only labels",
        labelsExclude = "Exclude labels",
        ageRestriction = "Age restrictions",
        ageRestrictionNone = "No restriction",
        ageRestrictionAllowOnly = "Allow only under",
        ageRestrictionExclude = "Exclude over"
    ),
    reader = ReaderStrings(
        zoom = "Zoom",
        readerType = "Reader type",
        readerPaged = "Paged",
        readerPanels = "Panels",
        readerContinuous = "Continuous",
        stretchToFit = "Stretch small images",
        decoder = "Image Decoder/Sampler",
        pagesInfo = "Pages info",
        pageNumber = "page",
        memoryUsage = "Memory usage",
        pageDisplaySize = "display size",
        pageOriginalSize = "original size",

        tapNavigation = "Tap Navigation",
        modeLeftRight = "Default",
        modeLeftRightDesc = "Left = previous page · Right = next page",
        modeRightLeft = "Reversed",
        modeRightLeftDesc = "Left = next page · Right = previous page",
        modeHorizontalSplit = "Top/Bottom Split",
        modeHorizontalSplitDesc = "Top half = previous page · Bottom half = next page",
        modeReversedHorizontalSplit = "Reversed Split",
        modeReversedHorizontalSplitDesc = "Top half = next page · Bottom half = previous page",
    ),
    pagedReader = PagedReaderStrings(
        scaleType = "Scale type",
        scaleScreen = "Screen",
        scaleFitWidth = "Fit width",
        scaleFitHeight = "Fit height",
        scaleOriginal = "Original",
        readingDirection = "Reading direction",
        readingDirectionLeftToRight = "Left to right",
        readingDirectionRightToLeft = "Right to left",
        layout = "Page layout",
        layoutSinglePage = "Single page",
        layoutDoublePages = "Double pages",
        layoutDoublePagesNoCover = "Double pages (no cover)",
        offsetPages = "Offset pages",
        adaptiveBackground = "Adaptive background",
    ),
    continuousReader = ContinuousReaderStrings(
        sidePadding = "Side padding",
        pageSpacing = "Page spacing",
        readingDirection = "Reading direction",
        readingDirectionTopToBottom = "Top to bottom",
        readingDirectionLeftToRight = "Left to right",
        readingDirectionRightToLeft = "Right to left",
    ),
    settings = SettingsStrings(
        language = "Interface language",
        languageSystem = "System language",
        serverSettings = "Server Settings",
        thumbnailSize = "Thumbnail size",
        thumbnailSizeDefault = "Default (300px)",
        thumbnailSizeMedium = "Medium (600px)",
        thumbnailSizeLarge = "Large (900px)",
        thumbnailSizeXLarge = "X-Large (1200px)",

        thumbnailRegenTitle = "Regenerate thumbnails",
        thumbnailRegenBody = "Thumbnails size has changed. Do you want to regenerate book thumbnails?",
        thumbnailRegenIfBigger = "YES, BUT ONLY IF BIGGER",
        thumbnailRegenAllBooks = "YES, ALL BOOKS",
        thumbnailRegenNo = "NO",

        deleteEmptyCollections = "Delete empty collections after scan",
        deleteEmptyReadLists = "Delete empty read lists after scan",
        taskPoolSize = "Task threads",
        rememberMeDurationDays = "Remember me duration (in days)",
        renewRememberMeKey = "Regenerate RememberMe key",
        serverPort = "Server port",
        serverContextPath = "Base URL",
        requiresRestart = "Requires restart to take effect",
        serverSettingsDiscard = "Discard",
        serverSettingsSave = "Save Changes",

        appTheme = "App Theme",
        appThemeDark = "Dark",
        appThemeLight = "Light",
        appThemeOled = "Darker",
        appThemeLightModern = "Light Modern",
        appThemeDarkModern = "Dark Modern",
        imageCardSize = "Image card size in grid view (minimum display size)",
        cardShadowLevel = "Card shadow level",
        cardCornerRadius = "Card corner radius",
        decoder = "Image Decoder/Sampler",
        epubReaderTypeKomga = "Komga Epub Reader",
        epubReaderTypeTtsu = "ッツ Ebook Reader",
        epubReaderTypeEpub3 = "EPUB3 Reader (Android)",
    ),
    errorCodes = ErrorCodes(
        err1000 = "File could not be accessed during analysis",
        err1001 = "Media type is not supported",
        err1002 = "Encrypted RAR archives are not supported",
        err1003 = "Solid RAR archives are not supported",
        err1004 = "Multi-Volume RAR archives are not supported",
        err1005 = "Unknown error while analyzing book",
        err1006 = "Book does not contain any page",
        err1007 = "Some entries could not be analyzed",
        err1008 = "Unknown error while getting book's entries",
        err1009 = "A read list with that name already exists",
        err1015 = "Error while deserializing ComicRack CBL",
        err1016 = "Directory not accessible or not a directory",
        err1017 = "Cannot scan folder that is part of an existing library",
        err1018 = "File not found",
        err1019 = "Cannot import file that is part of an existing library",
        err1020 = "Book to upgrade does not belong to provided series",
        err1021 = "Destination file already exists",
        err1022 = "Newly imported book could not be scanned",
        err1023 = "Book already present in ReadingList",
        err1024 = "OAuth2 login error: no email attribute",
        err1025 = "OAuth2 login error: no local user exist with that email",
        err1026 = "OpenID Connect login error: email not verified",
        err1027 = "OpenID Connect login error: no email_verified attribute",
        err1028 = "OpenID Connect login error: no email attribute",
        err1029 = "ComicRack CBL does not contain any Book element",
        err1030 = "ComicRack CBL has no Name element",
        err1031 = "ComicRack CBL Book is missing series or number",
        err1032 = "EPUB file has wrong media type",
        err1033 = "Some entries are missing",
        err1034 = "An API key with that comment already exists",
        err1035 = "Error while getting EPUB TOC",
        err1036 = "Error while getting EPUB Landmarks",
        err1037 = "Error while getting EPUB page list",
        err1038 = "Error while getting EPUB divina pages",
        err1039 = "Error while getting EPUB positions",
    ),
    ui = UiStrings(
        mapOf(
        // region generated-ui-strings
        "aCollectionWithThisName" to "A collection with this name already exists",
        "aReadListWithThis" to "A read list with this name already exists",
        "accentColorChipsTabs" to "Accent Color (chips & tabs)",
        "accountSettings" to "Account Settings",
        "actions" to "Actions",
        "active" to "active",
        "active2" to "Active",
        "add" to "Add",
        "addANote" to "Add a note…",
        "addBook" to "Add Book",
        "addCondition" to "Add condition",
        "addCustomRole" to "Add custom role",
        "addField" to "Add Field",
        "addFilter" to "Add Filter",
        "addLink" to "Add link",
        "addNewDiscordWebhook" to "Add New Discord Webhook",
        "addNote" to "Add Note",
        "addOtherAddressesThatReach" to "Add other addresses that reach the SAME Komga server (e.g. a local IP at home and a Tailscale address remotely). Switching keeps this profile, so your stats, ratings and links stay unified.",
        "addProvider" to "Add provider",
        "addTerm" to "Add term",
        "addToCollection" to "Add to collection",
        "addToReadList" to "Add to read list",
        "addUrl" to "Add URL",
        "addUrl2" to "Add Url",
        "addUser" to "Add User",
        "addWebhook" to "Add Webhook",
        "addsADedicatedButtonTo" to "Adds a dedicated button to the bottom navigation bar for ",
        "addsADedicatedStatsButton" to "Adds a dedicated stats button to the bottom navigation ",
        "addsAGenreTabTo" to "Adds a Genre tab to each library, grouping series by their kora:genre:* tags. Requires a connection to the server.",
        "addsFeaturesAimedAtMetadata" to "Adds features aimed at metadata updates and editing",
        "admin" to "Admin",
        "administrator" to "Administrator",
        "age" to "Age",
        "ageRating" to "Age Rating",
        "aggregate" to "Aggregate",
        "aggregateAndCombineMetadataFrom" to "aggregate and combine metadata from all enabled providers instead of taking first matched result",
        "aggregationSettings" to "Aggregation settings",
        "align" to "Align",
        "all" to "All",
        "all2" to "ALL",
        "allLibraries" to "All Libraries",
        "alreadyContainsThisBook" to "already contains this book",
        "alreadyContainsThisSeries" to "already contains this series",
        "alternateTitle" to "Alternate title",
        "alternateUrlsForThisServer" to "Alternate URLs for this server",
        "alternativeSeriesTitles" to "Alternative Series Titles",
        "alternativeTitleFallback" to "Alternative Title Fallback",
        "alternativeTitleLanguagesIso639" to "Alternative title languages (ISO 639)",
        "alternativeTitles" to "Alternative titles",
        "alwaysShowProgressBarWhile" to "Always show progress bar while reading",
        "analyze" to "Analyze",
        "analyzeLibrary" to "Analyze library",
        "analyzeWithAnilist" to "Analyze with AniList",
        "analyzing" to "Analyzing…",
        "anilistLinkSuggestionsOnline" to "AniList link suggestions (online)",
        "anilistSuggestions" to "AniList suggestions",
        "announcements" to "Announcements",
        "annuler" to "Cancel",
        "apiForCrossPlatformEfficient" to " API for cross-platform efficient GPU access using system's underlying Vulkan, Metal, or Direct3D 12 technologies",
        "appRestartIsRequiredFor" to "App restart is required for changes to take effect",
        "appSettings" to "App Settings",
        "appUpdates" to "App Updates",
        "appearance" to "Appearance",
        "appendVolumeToSeriesTitle" to "Append volume to series title",
        "appliedOnTheNextApp" to "Applied on the next app start.",
        "appliesToBookAndSeries" to "Applies to book and series pages. Off = every role Komga provides",
        "applyAnyway" to "apply anyway",
        "applyBackup" to "Apply backup?",
        "appriseGithubPage" to "Apprise github page",
        "artistRoles" to "Artist Roles",
        "attemptToOrderBooksUsing" to "Attempt to order books using naming pattern based on selected library type",
        "aucunTagPRimTout" to "No stale tag. Everything is up to date.",
        "aucune" to "(none)",
        "aucuneSRieMasquE" to "No hidden series. Long-press a series and choose “Hide for everyone”.",
        "authenticationActivity" to "Authentication Activity",
        "author" to "Author",
        "authorRoles" to "Author Roles",
        "authors" to "Authors",
        "autoDetectDirectionUseSeries" to "Auto-detect direction (use series metadata)",
        "autoDetectReadingDirection" to "Auto-detect reading direction",
        "autoDetectWebtoon" to "Auto-detect webtoon",
        "autoDetectWebtoonSwitchTo" to "Auto-detect webtoon (switch to vertical scroll)",
        "autoDownload" to "Automatic downloads",
        "autoDownloadBooksAhead" to "Volumes kept ready per series",
        "autoDownloadDescription" to "Off by default. Once on, the app keeps the next volumes of the series you are reading ready to read offline, within the limits below.",
        "autoDownloadExclude" to "Never download automatically",
        "autoDownloadLibrariesDescription" to "Leave empty to draw from every library.",
        "autoDownloadMaxSeries" to "Series followed",
        "autoDownloadOrder" to "Pinned series come first, then the ones you read most recently.",
        "autoDownloadPin" to "Always keep offline",
        "autoDownloadUnexclude" to "Allow automatic download",
        "autoDownloadUnpin" to "Stop keeping offline",
        "autoIdentify" to "Auto-Identify",
        "autoIdentifyKomf" to "Auto-Identify (Komf)",
        "autoSkipBlankPages" to "Auto-skip blank pages",
        "automaticBackups" to "Automatic backups",
        "automaticallyScanPagesForText" to "Automatically scan pages for text",
        "back" to "Back",
        "backToAuthors" to "Back to authors",
        "backToOnline" to "Back to online",
        "backToResults" to "Back to results",
        "backupFolder" to "Backup folder",
        "backupNow" to "Backup now",
        "backupRestore" to "Backup & restore",
        "backupRestore2" to "Backup & Restore",
        "betterTranslation" to "Better translation",
        "bibliothQuesDansToutes" to "Libraries in “All”",
        "bibliothQuesInclusesDansToutes" to "Libraries included in “All”",
        "biggerThanThisTheLists" to "Bigger than this — the lists below have everything.",
        "black" to "Black",
        "blackBubbleWhiteTextArtwork" to "Black bubble, white text — artwork untouched. Reduces glare. Bubbles with screentone or gradient backgrounds are left as-is.",
        "blackBubbleWhiteTextArtwork2" to "Black bubble, white text — artwork untouched. Reduces glare. Bubbles with screentone or gradient backgrounds are left as-is. Also available in the in-reader settings.",
        "body" to "Body",
        "bookCount" to "Book Count",
        "bookCovers" to "Book Covers",
        "bookFilters" to "Book Filters",
        "bookMetadata" to "Book metadata",
        "bookTitleExample" to "Book Title Example",
        "bookmarks" to "Bookmarks",
        "books" to "Books",
        "booksFinished" to "books finished",
        "bottomMargin" to "Bottom margin",
        "browse" to "Browse",
        "byDefaultBooksInA" to "By default, books in a read list are ordered manually. You can disable manual ordering to sort books by release date.",
        "byDefaultSeriesInA" to "By default, series in a collection will be ordered by name. You can enable manual ordering to define your own order.",
        "canBeSlowForHigh" to "can be slow for high resolution images",
        "cancel" to "Cancel",
        "cancel2" to "CANCEL",
        "cancelAllCurrentlyRunningTasks" to "Cancel all currently running tasks",
        "cancelAllTasks" to "Cancel all tasks",
        "cancelLoginAttempt" to "Cancel login attempt",
        "cardLayoutOverlayBackground" to "Card layout overlay background",
        "cards" to "Cards",
        "category" to "Category",
        "changeLocation" to "Change location",
        "changePassword" to "Change Password",
        "channel" to "Channel",
        "chapterManagement" to "Chapter management",
        "chapterManagementAmbiguous" to "Several possible matches — pick one",
        "chapterManagementAmbiguousCount" to "to decide",
        "chapterManagementConfirmBulk" to "Each selected series with a single confident match will be linked to its volumes. Series with several possible matches are left for you to decide.",
        "chapterManagementDescription" to "Pairs series released chapter by chapter with the collected volumes they belong to. Admin only.",
        "chapterManagementEmpty" to "No chapter series here.",
        "chapterManagementErrors" to "Errors (also in the log file):",
        "chapterManagementFailedCount" to "failed",
        "chapterManagementFindMatch" to "Find match",
        "chapterManagementLinked" to "Linked to its volumes",
        "chapterManagementLinkedCount" to "linked",
        "chapterManagementLinkedOnly" to "Linked",
        "chapterManagementLocalOnly" to "Link sharing via Komga is off, or you are not an admin: the pairings made here stay on this device only. Turn it on in Settings -> Navigation.",
        "chapterManagementMatchSelected" to "Match selection",
        "chapterManagementNoMatch" to "No match found",
        "chapterManagementNoMatchCount" to "without a match",
        "chapterManagementReport" to "What happened",
        "chapterManagementUnlink" to "Unlink",
        "chapterManagementUnlinked" to "Not linked",
        "chapterManagementUnlinkedOnly" to "Unlinked",
        "chapters" to "Chapters",
        "character" to "Character",
        "checkFoldersForNewOr" to "Check folders for new or removed books.\nUses the last modified time of parent folders",
        "checkForUpdates" to "Check for updates",
        "checkForUpdatesOnStartup" to "Check for updates on startup",
        "choisirLaCouverture" to "Choose cover",
        "choose" to "CHOOSE",
        "chooseAnImageDragAnd" to "Choose an image - drag and drop",
        "chooseLibrary" to "Choose a library",
        "chooseOnnxRuntimeVersion" to "Choose ONNX Runtime version",
        "chooseWhichAuthorRolesTo" to "Choose which author roles to show",
        "cleanupIncludeManual" to "Also delete books downloaded by hand",
        "cleanupIncludeManualDescription" to "Off by default: a book you asked for yourself is never removed automatically.",
        "cleanupNow" to "Clean up now",
        "cleanupReadAfterDays" to "Delete books once read for",
        "cleanupReadAfterDaysDescription" to "Only books you finished are ever removed. A book you are part-way through stays.",
        "clear" to "Clear",
        "clearAll" to "Clear all",
        "clearEpubCache" to "Clear EPUB cache",
        "clearImageCache" to "Clear image cache",
        "clickOnItemsToSelect" to "Click on items to select or deselect them",
        "clickToSelectDragTo" to "Click to select, drag to change order",
        "close" to "Close",
        "closeBook" to "Close Book",
        "closeMenu" to "Close menu",
        "collection" to "collection",
        "collection2" to "Collection",
        "collections" to "Collections",
        "colorCorrection" to "Color Correction",
        "columns" to "Columns",
        "comicBookArchives" to "Comic Book archives",
        "comicvineClientId" to "ComicVine client id",
        "completed" to "Completed",
        "computingSuggestions" to "Computing suggestions…",
        "condition" to "Condition",
        "confirm" to "Confirm",
        "confirmerEtAppliquer" to "Confirm and apply",
        "connectToANewServer" to "Connect to a new server",
        "connected" to "Connected",
        "connectedServers" to "Connected Servers",
        "connection" to "Connection",
        "contentSettings" to "Content",
        "continueReading" to "Continue Reading",
        "continueReading2" to "Continue reading",
        "continuous" to "Continuous",
        "copiedToClipboard" to "Copied to clipboard",
        "copy" to "Copy",
        "copyStacktraceToClipboard" to "Copy stacktrace to clipboard",
        "corner" to "Corner",
        "couldNotComputeSuggestions" to "Could not compute suggestions.",
        "couldNotConnectToThe" to "Could not connect to the server. Would you like to switch to offline mode?",
        "cover" to "Cover",
        "coverSettings" to "Cover settings",
        "crashLogs" to "Crash Logs",
        "create" to "Create",
        "cropBorders" to "Crop borders",
        "cudaNvidiaGpusRequiresCuda12" to "Cuda (Nvidia GPUs, requires CUDA12 and cuDNN9 system install)",
        "current" to "Current:",
        "current2" to "Current",
        "currentVersion" to "Current version:",
        "curves" to "Curves",
        "customTileAppearance" to "Custom tile appearance",
        "customUrl" to "Custom URL",
        "datasourceType" to "Datasource type",
        "days" to "Days",
        "deepScanAllLibraries" to "Deep scan all libraries",
        "default" to "Default",
        "defaultSeriesLanguage" to "Default series language",
        "defaultSeriesReadingDirection" to "Default series reading direction",
        "defaultValues" to "Default values",
        "delete" to "Delete",
        "deleteAll" to "Delete all",
        "deleteAnnotation" to "Delete annotation",
        "deleteBook" to "Delete Book",
        "deleteBookmark" to "Delete bookmark",
        "deleteBooks" to "Delete Books",
        "deleteCollection" to "Delete Collection",
        "deleteDownloaded" to "Delete downloaded",
        "deleteDownloadedBook" to "Delete downloaded Book",
        "deleteDownloadedBooks" to "Delete downloaded books",
        "deleteDownloadedLibrary" to "Delete downloaded Library",
        "deleteDownloadedSeries" to "Delete downloaded series",
        "deleteDownloadedSeries2" to "Delete downloaded Series",
        "deleteFromServer" to "Delete from server",
        "deleteItemsMarkedAsUnavailable" to "Delete items marked as unavailable",
        "deleteLibrary" to "Delete Library",
        "deletePreset" to "Delete Preset",
        "deleteReadList" to "Delete Read List",
        "deleteSavedSearch" to "Delete this saved search",
        "deleteSeries" to "Delete series",
        "deleteSeries2" to "Delete Series",
        "deleteSeriesFromServer" to "Delete series from server",
        "deleteServer" to "Delete Server",
        "deleteServerProfile" to "Delete Server Profile",
        "deleteUser" to "Delete User",
        "description" to "Description",
        "description4096CharactersMax" to "Description. 4096 characters max",
        "diagnostics" to "Diagnostics",
        "direction" to "Direction",
        "directmlAnyGpu" to "DirectML (any GPU)",
        "discard" to "Discard",
        "discordMarkdownText101" to "Discord Markdown Text 101",
        "dismiss" to "Dismiss",
        "display" to "Display",
        "displayTheBottomNavigationBar" to "Display the bottom navigation bar on series, book, and oneshot screens",
        "displayedNameEmptyDefault" to "Displayed name (empty = default)",
        "done" to "Done",
        "download" to "Download",
        "downloadComplete" to "Download Complete ",
        "downloadCuda12" to "download CUDA12",
        "downloadCudnn9" to "download cuDNN9",
        "downloadModel" to "Download Model",
        "downloadModel2" to "Download model",
        "downloadModels" to "Download Models",
        "downloadOnnxRuntime" to "Download ONNX Runtime",
        "downloadPolicy" to "Download policy",
        "downloadStorageLimit" to "Storage limit",
        "downloadStorageLimitDescription" to "When the limit is reached, finished books are removed oldest first. Downloads you start yourself are never blocked.",
        "downloadStorageUsed" to "Space used",
        "downloadTensorrt" to "download TensorRT",
        "downloadWhileChargingOnly" to "Download only while charging",
        "downloadWhileChargingOnlyDescription" to "Downloads wait for the charger instead of being cancelled. Leave off if you download on battery.",
        "downloadWifiOnly" to "Download over Wi-Fi only",
        "downloadWifiOnlyDescription" to "Off by default. Left off, downloads use mobile data and a volume can weigh tens of megabytes.",
        "downloaded" to "Downloaded",
        "downloading" to "Downloading...",
        "downloadingMangabakaDatabase" to "Downloading MangaBaka database",
        "downloadingOnnxRuntime" to "Downloading ONNX Runtime",
        "downloads" to "Downloads",
        "duplicateSeries" to "Duplicates",
        "duplicateSeriesClearIgnored" to "Restore ignored",
        "duplicateSeriesDescription" to "Series filed twice inside the same library. The scan reads the local index and sends no request to the server; only the Details button does, for one group at a time. Admin only.",
        "duplicateSeriesDetails" to "Details",
        "duplicateSeriesEmpty" to "No duplicate found.",
        "duplicateSeriesGroups" to "groups",
        "duplicateSeriesInvolved" to "series involved",
        "duplicateSeriesLanguageMissing" to "The index holds no language yet, so editions of one work still count as duplicates. Rebuild it from Maintenance.",
        "duplicateSeriesLikely" to "Duplicates",
        "duplicateSeriesNoLanguage" to "series have no language on the server, so two editions of one work can still be listed below.",
        "duplicateSeriesNoMatch" to "No group matches this filter.",
        "duplicateSeriesNotDuplicates" to "Not a duplicate",
        "duplicateSeriesNotIndexed" to "Not indexed, therefore not scanned:",
        "duplicateSeriesOpen" to "Open the series",
        "duplicateSeriesRescan" to "Scan again",
        "duplicateSeriesScanned" to "series scanned",
        "duplicateSeriesSearch" to "Filter by title",
        "duplicateSeriesShowMore" to "Show more",
        "duplicateSeriesUnsure" to "To check",
        "duplicateSeriesUnsureHint" to "Large groups sharing one title. Usually a collection name rather than the same work.",
        "edit" to "Edit",
        "editModeClickToSelect" to "Edit mode: Click to select, drag to change order",
        "editUser" to "Edit User",
        "email" to "Email",
        "emptyTrash" to "Empty trash",
        "emptyTrashForAllLibraries" to "Empty trash for all libraries",
        "emptyTrashForLibrary" to "Empty trash for library",
        "enableAutomaticBackups" to "Enable automatic backups",
        "enableIgnoreList" to "Enable ignore list",
        "enableKomfIntegration" to "Enable Komf Integration",
        "enableMetadataUpdateJobsFor" to "Enable metadata update jobs for libraries",
        "enableNcnnUpscalerMobileOnly" to "Enable NCNN upscaler (Mobile only)",
        "enableNotificationJobsForLibraries" to "Enable notification jobs for libraries",
        "enableTextSelection" to "Enable Text Selection",
        "enabled" to "Enabled",
        "engine" to "Engine",
        "enterANameForThe" to "Enter a name for the preset",
        "epub" to "Epub",
        "epub3ReaderIsNotAvailable" to "EPUB3 reader is not available on this platform.",
        "epubReader" to "Epub Reader",
        "epubReaderSettings" to "Epub Reader Settings",
        "error" to "Error",
        "errorLoadingPage" to "This page could not be loaded",
        "errors" to "Errors",
        "eventListener" to "Event Listener",
        "exclusionMode" to "Exclusion mode",
        "exit" to "Exit",
        "experimental" to "Experimental",
        "export" to "Export…",
        "exportLogs" to "Export logs…",
        "failed" to "Failed",
        "failedToLoadMetadata" to "Failed to load metadata",
        "failedToParseUrl" to "failed to parse URL",
        "favoris" to "Favourites",
        "favoris2" to "Favourites",
        "female" to "Female",
        "fermer" to "Close",
        "fermer2" to "Close",
        "fieldName256CharactersMax" to "Field name. 256 characters max",
        "fieldValue1024CharactersMax" to "Field value. 1024 characters max",
        "file" to "File",
        "fileDownload" to "File Download",
        "filter" to "Filter",
        "filterExcluded" to "excluded",
        "filterLetter" to "Letter",
        "filterRating" to "Rating",
        "filterTag" to "Tag",
        "finishYourFirstBookTo" to "Finish your first book to see stats appear here.",
        "finished" to "Finished:",
        "flashDuration" to "Flash Duration",
        "flashEvery" to "Flash every",
        "flashOnPageChange" to "Flash on page change",
        "flashWith" to "Flash with",
        "floatingNavBarKeepReading" to "Floating nav bar, Keep Reading panel, and pill-shaped tabs",
        "floatingNavigationBar" to "Floating navigation bar",
        "fonctions" to "Features",
        "font" to "Font",
        "fontGroupAccessible" to "Legibility",
        "fontGroupSerif" to "For reading",
        "fontGroupSystem" to "System",
        "fontGroupYours" to "Yours",
        "fontSize" to "Font size",
        "fontText" to "Font & Text",
        "footer2048CharactersMax" to "Footer. 2048 characters max",
        "forYou" to "For you",
        "forceTheScannerToCompare" to "Force the scanner to compare all scanned books with the ones stored in the database",
        "format" to "Format",
        "forward30Seconds" to "Forward 30 seconds",
        "frequency" to "Frequency",
        "fullFeaturedWebClientFor" to "Full-featured web client for Komga",
        "fuzzy" to "≈ Fuzzy",
        "gRer" to "Manage",
        "gamma" to "Gamma",
        "general" to "General",
        "genre" to "Genre",
        "genreTab" to "Genre tab",
        "genreTileAppearance" to "Genre tile appearance",
        "genres" to "Genres",
        "genres2" to "Genres: ",
        "giveGenreTilesTheirOwn" to "Give genre tiles their own size and text style instead of the global card appearance.",
        "glossaryForThisSeries" to "Glossary for this series",
        "goBack" to "Go back",
        "goOffline" to "Go Offline",
        "goOffline2" to "Go offline",
        "goOfflineAsCurrentUser" to "Go offline as current user",
        "goOnline" to "Go online",
        "gotIt" to "Got it",
        "gridSize" to "Grid Size",
        "group" to "Group",
        "hideBooksFromTheseLibraries" to "Hide books from these libraries:",
        "hideChapterSeries" to "Hide chapter series (Chap)",
        "hideParenthesesInNames" to "Hide parentheses in names",
        "highPerformanceHardwareAcceleratedDirectx" to "High-performance, hardware-accelerated DirectX 12 library for machine learning",
        "highlight" to "Highlight",
        "highlightCompleteSeries" to "Highlight complete series",
        "home" to "Home",
        "identifyKomf" to "Identify (Komf)",
        "ifAggregateOptionIsEnabled" to "if aggregate option is enabled merge genres instead of taking them from first matched result",
        "ifAggregateOptionIsEnabled2" to "if aggregate option is enabled merge tags instead of taking them from first matched result",
        "ifEntryAlreadyHasA" to "If entry already has a user uploaded cover, mark newly uploaded cover as current.\nIf disabled, then upload cover without selecting it",
        "ifTheFirst3Pages" to "If the first 3 pages are very tall (height ≥ 4× width), switch to panel-by-panel reader (auto-zoom on each panel). Your manual override sticks for the rest of the reader session.",
        "ignoreList" to "Ignore List",
        "ignoredSeriesAndTheirBooks" to "Ignored series and their books are hidden everywhere (libraries, collections, search, home, genres). Local only — never sent to the server.",
        "image" to "Image",
        "imageReader" to "Image Reader",
        "imageSettings" to "Image Settings",
        "immersiveCardColor" to "Immersive card color",
        "import" to "Import…",
        "importAnImage" to "Import an image…",
        "importIsbnWithinBarcode" to "Import ISBN within barcode",
        "importLocalMediaAssets" to "Import local media assets",
        "importMetadataForCbrCbz" to "Import metadata for CBR/CBZ containing a ComicInfo.xml file",
        "importMetadataFromEpubFiles" to "Import metadata from EPUB files",
        "importMetadataGeneratedByMylar" to "Import metadata generated by Mylar",
        "importSettings" to "Import settings",
        "importerDesCouverturesDossier" to "Import covers (folder)…",
        "inTheContinuousReaderA" to "In the continuous reader, a screen tap crosses blank gutters whole and stops on panel and speech-bubble boundaries instead of advancing a blind 80%. Falls back to the fixed distance when a page can't be analysed. Also available in the in-reader settings.",
        "includeLinks" to "Include links",
        "inclusionMode" to "Inclusion mode",
        "info" to "Info",
        "inline" to "Inline",
        "input" to "Input",
        "install" to "Install",
        "installed" to "Installed",
        "invalidWebhookUrl" to "Invalid webhook URL",
        "invertSpeechBubbles" to "Invert speech bubbles",
        "isbn" to "ISBN",
        "isbnBarcode" to "ISBN barcode",
        "jeton24CaractResMin" to "Token (24 characters min)",
        "jobHistory" to "Job History",
        "kavitaApiKey" to "Kavita API Key",
        "kavitaProcessing" to "Kavita Processing",
        "kavitaUrl" to "Kavita Url",
        "keepScreenOnWhileReading" to "Keep screen on while reading",
        "key" to "Key",
        "komfSeriesAutoIdentify" to "Komf series auto-identify",
        "komfSettings" to "Komf Settings",
        "komfUrl" to "Komf Url",
        "komgaLogin" to "Komga Login",
        "komgaPassword" to "Komga Password",
        "komgaProcessing" to "Komga Processing",
        "komgaToolkit" to "Komga Toolkit",
        "komgaUrl" to "Komga Url",
        "komgaUsername" to "Komga Username",
        "komgaWebui" to "Komga webui",
        "komgaWebuiEpubReaderAdapted" to "Komga webui epub reader adapted for use in Kora",
        "label" to "Label",
        "labels" to "Labels",
        "lancer" to "Run",
        "lancerEtAppliquer" to "Run and apply?",
        "language" to "Language",
        "lastRead" to "Last read:",
        "latestCheckedVersion" to "Latest checked version:",
        "launchProcessingJobsWhenNew" to "Launch processing jobs when new series or book is added",
        "leave" to "Leave",
        "levels" to "Levels",
        "libraries" to "Libraries",
        "library" to "Library",
        "librarySRootFolder" to "Library's root folder",
        "librarySwitcherInPageTitle" to "Library switcher in page title",
        "libraryTypeAffectsSomeOptions" to "Library type. Affects some options, mainly book name parsing",
        "lifetime" to "Lifetime",
        "limit" to "Limit",
        "lineHeight" to "Line height",
        "linearLightDownsampling" to "Linear light downsampling",
        "links" to "Links",
        "lire" to "To read",
        "lire2" to "To read",
        "list" to "List",
        "listening" to "Listening…",
        "loadFont" to "Load font…",
        "loadSmallPreviews" to "Load small previews",
        "loadSmallPreviewsWhenDragging" to "Load small previews when dragging navigation slider",
        "localArtwork" to "Local artwork",
        "localDownloadOutdated" to "Local download outdated",
        "lockScreenRotation" to "Lock screen rotation",
        "logOut" to "Log Out",
        "login" to "Login",
        "login2" to "login",
        "loginWithAnotherAccount" to "Login with another account",
        "logs" to "Logs",
        "maintenance" to "Maintenance",
        "male" to "Male",
        "manageConnectedServers" to "Manage Connected Servers",
        "mangabakaOfflineDatabase" to "MangaBaka Offline Database",
        "mangajanaiOnnxModelsPreset" to "MangaJaNai ONNX models preset",
        "manualOrdering" to "Manual ordering",
        "margins" to "Margins",
        "markAsRead" to "Mark as read",
        "markAsUnread" to "Mark as unread",
        "masquerPourTous" to "Hide for everyone?",
        "maximumLogSize" to "Maximum log size",
        "mediaManagement" to "Media Management",
        "mediaType" to "Media Type",
        "median2000MsTheServer" to "Median ≥ 2000 ms: the server is the bottleneck, not the app.",
        "menu" to "Menu",
        "mergeAdjacentTextBlocksInto" to "Merge adjacent text blocks into a single block",
        "mergeGenres" to "Merge Genres",
        "mergeTags" to "Merge Tags",
        "mergeTextSegments" to "Merge text segments",
        "metadata" to "Metadata",
        "metadataProvidersSettings" to "Metadata Providers Settings",
        "metadataUpdateJobs" to "Metadata Update Jobs",
        "model" to "Model",
        "modelUrlSource" to "Model URL Source",
        "modernTopAppBarAnd" to "Modern top app bar and updated item cards",
        "more" to "More",
        "morphingCoverImageThatFlies" to "Morphing cover image that flies to thumbnail on expand",
        "morphingImmersiveCover" to "Morphing Immersive Cover",
        "myAccount" to "My Account",
        "myAuthenticationActivity" to "My Authentication Activity",
        "myReadingStats" to "My Reading Stats",
        "myanimelistClientId" to "MyAnimeList client id",
        "name" to "Name",
        "nameMatchingMode" to "Name matching mode",
        "nativeEpub3ReaderWith" to "Native EPUB 3 reader with synchronized audio overlay (SMIL) support. Android only.",
        "navigation" to "Navigation",
        "ncnnUpscalerLogs" to "NCNN / Upscaler Logs",
        "never" to "Never",
        "newLibraryUi" to "New library UI",
        "newPassword" to "New password",
        "newUi2" to "New UI 2",
        "newVersionIsAvailable" to "New version is available",
        "next" to "Next",
        "next2" to "Next:",
        "nextChapter" to "Next chapter",
        "nextPage" to "Next page",
        "nextSegment" to "Next segment",
        "nextVolume" to "Next volume",
        "nightMode" to "Night mode",
        "nightModeFrom" to "From",
        "nightModeIntensity" to "Warmth",
        "nightModeSchedule" to "Only during a time range",
        "nightModeTo" to "To",
        "nightModeWarmTintOnPages" to "Warms the pages to cut blue light. The menus are left alone.",
        "noAnnotationsYet" to "No annotations yet",
        "noBookmarksYet" to "No bookmarks yet",
        "noBooks" to "No books",
        "noChaptersAvailable" to "No chapters available",
        "noGenresFoundInThis" to "No genres found in this library. Add kora:genre:* tags to your series in Komga.",
        "noIgnoredSeriesLongPress" to "No ignored series. Long-press a series and choose Ignore.",
        "noLinksYetUseAdd" to "No links yet. Use “Add link” to mark other versions (another ",
        "noNextSeriesWithThe" to "No next series with the current filters",
        "noReadingActivityYet" to "No reading activity yet",
        "noResults" to "No results",
        "noSavedSearches" to "No saved search yet",
        "noWorksFoundForThis" to "No works found for this author",
        "nonDisponibleSurCettePlateforme" to "Not available on this platform.",
        "none" to "None",
        "notDownloaded" to "Not downloaded",
        "note" to "Note",
        "notes" to "Notes",
        "nothingToShow" to "Nothing to show",
        "notificationContext" to "Notification Context",
        "notificationSettings" to "Notification Settings",
        "notificationTemplate" to "Notification Template",
        "notifications" to "Notifications",
        "number" to "Number",
        "ocrEngine" to "OCR Engine",
        "offline" to "Offline",
        "offlineMode" to "Offline mode",
        "offlineMode2" to "Offline Mode",
        "ok" to "OK",
        "oncePerLibrarySuggestionsAre" to "Once per library. Suggestions are then computed on the device.",
        "onnxModelPath" to "ONNX model path",
        "onnxRuntimeSupportIsExperimental" to "ONNX Runtime support is experimental.\nMight cause crashes or other app instabilities",
        "onnxruntimeUpscaleMode" to "OnnxRuntime upscale mode",
        "openInKomga" to "Open in Komga",
        "openMenu" to "Open menu",
        "openStats" to "Open stats",
        "operator" to "Operator",
        "orderBooks" to "Order Books",
        "originalSeries" to "Original series",
        "otherOptions" to "Other Options",
        "otherTags" to "Other tags",
        "otherwiseThePillSitsAt" to "Otherwise the pill sits at the top-left of the cover",
        "otherwiseTheTitleIsOverlaid" to "Otherwise the title is overlaid on the cover.",
        "output" to "Output",
        "outputLevels" to "Output Levels",
        "ouvrirLeWebui" to "Open the web UI",
        "overrideExistingCovers" to "Override Existing Covers",
        "overrideExistingPreset" to "Override existing preset",
        "pRimTresBibliothQue" to "Scopes (library per category)",
        "page" to "Page",
        "pageSpacing" to "Page spacing",
        "pageSpacing2" to "page spacing",
        "pageStreaming" to "Page Streaming",
        "paged" to "Paged",
        "pages" to "pages",
        "pagesRead" to "Pages read",
        "panelDetection" to "Panel Detection",
        "panels" to "Panels",
        "paraSpacing" to "Para spacing",
        "parent" to "Parent",
        "parody" to "Parody",
        "password" to "Password",
        "pauseAtTheLastPage" to "Pause at the last page instead of rolling silently into the next book. Swipe again to continue. Also ensures the current book gets marked as read.",
        "pdf" to "PDF",
        "pendingTask" to "1 pending task",
        "periodicallyWriteTheSameBackup" to "Periodically write the same backup file to a folder of your choice. ",
        "pickTheCorrectSeries" to "Pick the correct series",
        "pillAtBottomLeft" to "Pill at bottom-left",
        "plusTard" to "Later",
        "pointType" to "Point Type",
        "preferOriginalPublisherInsteadOf" to "Prefer original publisher instead of localizing publisher",
        "presetWithThatNameAlready" to "Preset with that name already exists",
        "presets" to "Presets",
        "preventTheApplicationScreenFrom" to "Prevent the application screen from rotating",
        "preventsGhostingOnEInk" to "Prevents ghosting on e-ink devices",
        "preview" to "Preview",
        "previous" to "Previous",
        "previous2" to "Previous:",
        "previousChapter" to "Previous chapter",
        "previousPage" to "Previous page",
        "previousSegment" to "Previous segment",
        "previousVolume" to "Previous volume",
        "processing" to "Processing...",
        "processing2" to "Processing",
        "prochainesSorties" to "Upcoming releases",
        "prochainesSorties2" to "Upcoming releases",
        "projectLink" to "Project Link",
        "projectOnGithub" to "Project on Github",
        "providers" to "Providers",
        "publisher" to "Publisher",
        "publisherStyles" to "Publisher styles",
        "purgerLeTag" to "Purge the tag",
        "rAfficher" to "Restore",
        "rInitialiser" to "Reset",
        "randomSeriesInLibrary" to "Random series in library",
        "rapidocrModel" to "RapidOCR Model",
        "rapidocrModels" to "RapidOCR Models",
        "rate" to "Rate",
        "ratingAny" to "Any",
        "ratingAtLeast1" to "Rated",
        "ratingAtLeast3" to "3 stars and up",
        "ratingAtLeast4" to "4 stars and up",
        "ratingExactly5" to "5 stars",
        "reAnalyseAllLibraries" to "Re-analyse all libraries",
        "reAnalyseLibrary" to "Re-analyse library",
        "reDownloadModel" to "Re-download Model",
        "reDownloadModels" to "Re-download Models",
        "reachedTheStartOfThe" to "Reached the start of the series",
        "read" to "Read",
        "readAloudHighlight" to "Read-aloud highlight",
        "readFromStart" to "Read from start",
        "readIncognito" to "Read incognito",
        "readIncognito2" to "Read Incognito",
        "readList" to "read list",
        "readList2" to "Read List",
        "readLists" to "Read Lists",
        "readLists2" to "Read lists",
        "readProgress" to "Read progress:",
        "readProgressWillNotBe" to "Read progress will not be synced",
        "readerSettings" to "Reader settings",
        "readerType" to "Reader Type",
        "reading" to "Reading",
        "readingMode" to "Reading mode",
        "readingMode2" to "Reading Mode",
        "readingOrder" to "Reading order",
        "readingOrderEdition" to "edition",
        "readingOrderEditions" to "editions",
        "readingOrderMainLine" to "Main line",
        "readingOrderNoDeclaredOrder" to "No declared order",
        "readingOrderReadAfter" to "Read after",
        "readingOrderSameWorld" to "Same world",
        "readingOrderShowAll" to "Show all",
        "readingOrderShowLess" to "Show less",
        "readingOrderSpinOffs" to "Spin-offs",
        "readingOrderStartHere" to "Start here",
        "readingStats" to "Reading stats",
        "readsSharedSeriesRelationsFrom" to "Reads shared series relations from the Komga server (visible to ",
        "rebuildTheReadingOrder" to "Rebuild the reading order",
        "recentDownloads" to "Recent downloads",
        "recentlyRead" to "Recently read",
        "recolorsTheTopRightBadge" to "Recolors the top-right badge on series cards when the series is Ended and every volume is owned",
        "refresh" to "Refresh",
        "refreshMetadata" to "Refresh metadata",
        "refreshMetadataForLibrary" to "Refresh metadata for library",
        "releaseDate" to "Release date",
        "releaseDate2" to "Release Date",
        "releaseDate3" to "Release date:",
        "releaseNotes" to "Release notes:",
        "reload" to "Reload",
        "remoteUnavailable" to "Remote Unavailable",
        "removeAnythingInParenthesesWhen" to "Remove anything in parentheses when displaying series and oneshot names",
        "removeComicinfoXml" to "Remove ComicInfo.xml?",
        "removeFilter" to "Remove filter",
        "removeModel" to "Remove model",
        "removeUrl" to "Remove URL",
        "renameGenre" to "Rename genre",
        "renommer" to "Rename",
        "repeatNewPassword" to "Repeat new password",
        "replaceTheBottomNavigationBar" to "Replace the bottom navigation bar with a floating toolbar",
        "requiresAddingThisHostAnd" to "Requires adding this host and port to Komga CORS configuration",
        "requiresAppRestartToTake" to "Requires app restart to take effect",
        "requiresWriteAccessToFiles" to "Requires write access to files",
        "resetAll" to "Reset All",
        "resetChannel" to "Reset Channel",
        "resetMetadataKomf" to "Reset Metadata (Komf)",
        "resetToDefault" to "Reset to default",
        "resetToInternal" to "Reset to internal",
        "respectPublisherColors" to "Respect publisher colors",
        "restart" to "Restart",
        "restore" to "Restore",
        "restoreAll" to "Restore all",
        "retour" to "Back",
        "retry" to "Retry",
        "returnBook" to "Return book",
        "returnHome" to "Return home",
        "returnLibrary" to "Return library",
        "returnSerie" to "Return serie",
        "rewind10Seconds" to "Rewind 10 seconds",
        "rienAppliquer" to "Nothing to apply.",
        "rocmAmdGpusRequiresRocm7" to "ROCm (AMD GPUs, requires ROCm7 system install)",
        "role" to "Role",
        "roles" to "Roles",
        "roles2" to "Roles:",
        "root" to "root",
        "rootFolder" to "Root folder",
        "runInBackground" to "Run in background",
        "running" to "Running",
        "sRiesMasquEs" to "Hidden series",
        "save" to "Save",
        "saveACopyOfYour" to "Save a copy of your settings, home filters, library filters ",
        "saveChanges" to "Save Changes",
        "saveImage" to "Save image",
        "savePreset" to "Save Preset",
        "saveSearch" to "Save search",
        "saveSearchName" to "Name of the search",
        "savedSearchReplaced" to "Replaces the search of the same name",
        "savedSearches" to "Saved searches",
        "savedSettings" to "Saved Settings",
        "scanAllLibraries" to "Scan all libraries",
        "scanForExistingFiles" to "Scan for existing files",
        "scanForTheseFileTypes" to "Scan for these file types",
        "scanLibraryFiles" to "Scan library files",
        "scanLibraryFilesDeep" to "Scan library files (deep)",
        "scanText" to "Scan Text",
        "scroll" to "Scroll",
        "search" to "Search",
        "searchASeriesByName" to "Search a series by name",
        "searchAll" to "Search all...",
        "searchCollections" to "Search collections",
        "searchOrCreateCollection" to "Search or create collection",
        "searchOrCreateReadList" to "Search or create read list",
        "searchReadlists" to "Search readlists",
        "searchResults" to "Search Results",
        "searchSeries" to "Search series",
        "searchSettings" to "Search settings",
        "select" to "Select",
        "selectAll" to "Select All",
        "selectText" to "Select Text",
        "selected" to "Selected",
        "selectionModeClickOnItems" to "Selection mode: Click on items to select or deselect them",
        "series" to "Series",
        "seriesCovers" to "Series Covers",
        "seriesMetadata" to "Series metadata",
        "seriesTitle" to "Series Title",
        "seriesTitleLanguageIso639" to "Series title language (ISO 639)",
        "server" to "Server",
        "serverManagement" to "Server Management",
        "serverSettings" to "Server Settings",
        "serverUnavailable" to "Server Unavailable",
        "serverUrl" to "Server Url",
        "serverUrlLoginAndReading" to "Server URL, login and reading progress are NOT included. ",
        "settings" to "Settings",
        "shareLibraries" to "Share Libraries",
        "shareSeriesLinksViaKomga" to "Share series links via Komga",
        "sharedOnServer" to "Shared on server",
        "sharingLabel" to "Sharing Label",
        "showASemiTransparentBackground" to "Show a semi-transparent background overlay behind the text on cards",
        "showDateTime" to "Show date & time",
        "showFullPage" to "Show full page",
        "showLanguageOnCovers" to "Show language on covers",
        "showLocation" to "Show location",
        "showNavigationBarInImmersive" to "Show navigation bar in immersive screens",
        "showSeriesCount" to "Show series count",
        "showStatsInBottomNavigation" to "Show stats in bottom navigation",
        "showTheNumberOfSeries" to "Show the number of series under each genre.",
        "showTitleAndMetadataBelow" to "Show title and metadata below the thumbnail instead of on top",
        "showUpcomingReleasesInBottom" to "Show upcoming releases in bottom navigation",
        "showsAThumbnailWhileDragging" to "Shows a thumbnail while dragging the navigation slider",
        "shutDownServer" to "Shut down server",
        "shutdown" to "Shutdown",
        "sidePadding" to "Side padding",
        "sidePadding2" to "side padding",
        "similar" to "Similar",
        "sinceV1010" to "since v1.0.10",
        "size" to "Size",
        "slowerButPotentiallyMoreAccurate" to "slower but potentially more accurate",
        "smallFrEnPillOn" to "Small FR/EN pill on series covers, only when the language is known",
        "smooth" to "Smooth",
        "sort" to "Sort",
        "sortNumber" to "Sort Number",
        "sorties" to "Releases",
        "specialUserThatHasAccess" to "Special user that has access to all downloaded books",
        "speechEngine" to "Speech Engine",
        "speechModelNotAvailableOn" to "Speech model not available on this device.\nRequires Android 12+ with Google speech model.",
        "splitLandscapePages" to "Split landscape pages",
        "startupScreen" to "Startup screen",
        "stats" to "Stats",
        "status" to "Status",
        "stopAtEndOfBook" to "Stop at end of book (continuous reader)",
        "stopKomgaApplicationProcess" to "Stop Komga application process",
        "storageLocation" to "Storage location",
        "streak" to "Streak",
        "successful" to "Successful",
        "suggestSameAuthorSimilarTitle" to "Suggest (same author / similar title)",
        "summary" to "Summary",
        "switch" to "Switch",
        "switchActiveUrl" to "Switch active URL",
        "switchLibrary" to "Switch library",
        "switchToThisServer" to "Switch to this server",
        "tagScoreThreshold" to "Tag score threshold",
        "tagSizeLimit" to "Tag size limit",
        "tags" to "Tags",
        "tapToZoom" to "Tap to zoom",
        "tappingInAVerticalStrip" to "Tapping in a vertical strip crosses blank gutters whole and stops on panel and speech-bubble boundaries, instead of a fixed distance.",
        "tensorrtNvidiaGpusRequiresCuda12" to "TensorRT (Nvidia GPUs, requires CUDA12, cuDNN9 and TensorRT system install)",
        "term" to "Term",
        "testSend" to "Test Send",
        "testTimeAugmentationSlowerBut" to "Test-Time Augmentation, slower but higher quality",
        "tester" to "Test",
        "text" to "Text",
        "textBelowCard" to "Text below card",
        "textDetectionLanguage" to "Text Detection Language",
        "theSearchReturnedNoResults" to "The search returned no results",
        "thereSNoNextBook" to "There's no next book",
        "thereSNoPreviousBook" to "There's no previous book",
        "theseFeaturesAreExperimentalThey" to "These features are experimental — they may change or be removed in a future version.",
        "thisMonth" to "This month",
        "thisWeek" to "This week",
        "thumbnail" to "Thumbnail",
        "tileSize" to "Tile size",
        "tintTheDetailCardBackground" to "Tint the detail card background with the cover's dominant color",
        "title" to "Title",
        "title256CharactersMax" to "Title. 256 characters max",
        "titleBelowCover" to "Title below cover",
        "titleSettings" to "Title Settings",
        "titleUrl" to "Title Url",
        "toggleBookmark" to "Toggle Bookmark",
        "toggleTheme" to "Toggle theme",
        "topMargin" to "Top margin",
        "total" to "Total",
        "toutPurger" to "Purge all",
        "toutRAfficher" to "Restore all",
        "toutes" to "All",
        "toutes2" to "All",
        "tracksBookCompletionsAndShows" to "Tracks book completions and shows your reading ",
        "translate" to "Translate",
        "translateFrom" to "Translate from",
        "translation" to "Translation",
        "trySearchingForSomethingElse" to "Try searching for something else",
        "ttaMode" to "TTA Mode",
        "twoSequelsNoOrderBetween" to "Two sequels, no order between them. Mark one as the sequel of the other to chain them.",
        "type" to "Type",
        "unavailable" to "Unavailable",
        "unknownSeries" to "Unknown series",
        "unlinkSeries" to "Unlink series",
        "unset" to "Unset",
        "update" to "Update",
        "updateModes" to "Update Modes",
        "updateOnnxRuntime" to "Update ONNX Runtime",
        "updateOrDownloadAnotherVersion" to "Update or download another version of ONNX Runtime",
        "updateSeriesAlternativeTitleIf" to "Update series alternative title if matched metadata contains alternative title data",
        "updateSeriesTitleIfMatched" to "Update series title if matched metadata contains title data",
        "updates" to "Updates",
        "updating" to "Updating",
        "uploadBookCovers" to "Upload book covers",
        "uploadSeriesCover" to "Upload series cover",
        "uploadSeriesCovers" to "Upload series covers",
        "upscalerSettings" to "Upscaler Settings",
        "upscaling" to "Upscaling",
        "url" to "URL",
        "urlToolkitHttpHTe" to "Toolkit URL (http://host:port)",
        "urls" to "Urls",
        "useFirstAvailableAlternativeTitle" to "Use first available alternative title if no main title with specified language is found",
        "useOriginalPublisher" to "Use Original Publisher",
        "useSeriesMetadataManualFlips" to "Use series metadata. Manual flips are stored locally per-series.",
        "userSettings" to "User Settings",
        "username" to "Username",
        "users" to "Users",
        "usesAppriseExecutableInstalledOn" to "Uses Apprise executable installed on the system.\nTemplates are rendered using Apache Velocity",
        "usesGoogleSOnDevice" to "Uses Google's on-device model. Downloads automatically when first used.",
        "usesMarkdownSyntaxTemplatesAre" to "Uses markdown syntax. Templates are rendered using Apache Velocity",
        "usesTensorrtToCreateOptimized" to "Uses TensorRT to create optimized graph engine. Takes a significant time on model first load. After initial load engine is cached for future use",
        "value" to "Value",
        "velocityTemplateLanguageSyntaxReference" to "Velocity Template Language syntax reference",
        "viewLogs" to "View logs",
        "viewLogs2" to "View Logs",
        "voiceSearch" to "Voice search",
        "volumeKeysNavigation" to "Volume keys navigation",
        "webgpuAnyGpu" to "WebGPU (Any GPU)",
        "webhookUrl" to "Webhook URL",
        "webhooks" to "Webhooks",
        "webtoonSmartScroll" to "Webtoon smart scroll",
        "whatSNew" to "What's new",
        "whenCropBordersIsOn" to "When Crop borders is on, blank pages are removed from the reader instead of crashing.",
        "whenOnTappingHomeLibrary" to "When on, tapping 'Home' / library-name at the top of ",
        "whichScreenKoraOpensTo" to "Which screen Kora opens to when you launch the app. ",
        "white" to "White",
        "whiteAndBlack" to "White and Black",
        "widgetProchainTome" to "“Next volume” widget",
        "write" to "Write",
        "wrongSeriesSearchAnilist" to "Wrong series? Search AniList",
        "youAreEditingAuthorsFor" to "You are editing authors for multiple books. This will override existing authors of each book.",
        "youAreEditingTagsFor" to "You are editing tags for multiple series. This will override existing tags of each series.",
        "youAreEditingTagsFor2" to "You are editing tags for multiple books. This will override existing tags of each book.",
        "youHaveUnsavedChanges" to "You have unsaved changes",
        "yourRating" to "Your rating",
        "yourReading" to "Your reading",
    // endregion
        "user" to "User",
        "online" to "Online",
        "sharedLibraries" to "Shared Libraries",
        "contentRestriction" to "Content Restriction",
        "sharing" to "Sharing",
        "scanner" to "Scanner",
        "providerSettings" to "Provider settings",
        "poster" to "Poster",
        "options" to "Options",
        "alternateTitles" to "Alternate titles",
        "cardWidthGap" to "Width Gap",
        "cardHeightGap" to "Height Gap",
        "cardSpacingBelow" to "Spacing Below",
        "noBookFinishedThisMonth" to "No book finished this month",
        "oneBookThisMonth" to "1 book this month",
        "booksThisMonth" to "{n} books this month",
        "oneDayStreak" to "1-day streak",
        "dayStreak" to "{n}-day streak",
        )
    ),
    shelves = ShelfStrings(
        keepReading = "Keep reading",
        onDeck = "On deck",
        recentlyReleasedBooks = "Recently released books",
        recentlyAddedBooks = "Recently added books",
        recentlyAddedSeries = "Recently added series",
        recentlyUpdatedSeries = "Recently updated series",
        recentlyReadBooks = "Recently read books",
        discover = "Discover",
        forgotten = "Forgotten",
        almostFinished = "Almost finished",
    ),
    editions = EditionStrings(
        heading = "Also available as",
        otherVersion = "Another version",
        otherLanguage = "Another language",
        colourEdition = "Colour edition",
        chapters = "Chapters",
        volumes = "Volumes",
    ),
    roles = RoleStrings(
        writer = "Writer",
        penciller = "Penciller",
        inker = "Inker",
        colorist = "Colorist",
        letterer = "Letterer",
        cover = "Cover",
        editor = "Editor",
        translator = "Translator",
    ),
    shelfPatterns = ShelfPatternStrings(
        custom = "Custom",
        onDeck = "On deck",
        forgotten = "Forgotten",
        recentlyAdded = "Recently added",
        recentlyUpdated = "Recently updated",
        almostFinished = "Almost finished",
        favorites = "Favourites",
        series = "Series",
        book = "Book",
        discover = "Discover",
    ),
    counts = CountStrings(
        selected = { "$it selected" },
        pages = { "$it Pages" },
        pagesLeft = { "$it pages left" },
        bookAndPages = { number, pages -> "Book #$number · $pages pages" },
        seriesCount = { "$it series" },
        booksCount = { "$it books" },
        rolesFor = { "Roles for $it" },
        inLibrary = { "in $it" },
        releaseYear = { "Release Year: $it" },
        processedFiles = { "Processed $it files" },
    ),
    navigation = NavigationStrings(
        libraries = "Libraries",
        home = "Home",
        search = "Search",
        stats = "Stats",
        releases = "Releases",
        settings = "Settings",
    ),
    suggestions = SuggestionStrings(
        closestMatches = "Closest matches",
        moreForYou = "More for you",
        becauseYouLiked = { "Because you liked $it" },
        becauseYouRead = { "Because you read $it" },
        becauseYouAreReading = { "Because you are reading $it" },
        showRead = "Show read",
        buildingProfile = "Building your profile…",
        analysingLibrary = { "Analysing the library… $it %" },
        failed = "Could not compute suggestions.",
        emptyNoProfile = "Nothing to go on yet. Read or rate a few series in this library and " +
            "suggestions will appear here.",
        emptyAllRead = "No suggestion left. Try showing the series you have already read.",
        profileSize = { "Based on $it series you have read or rated" },
        resetDismissed = { "Reset not interested ($it)" },
        markPlanned = "Mark as to read",
        unmarkPlanned = "Remove from to read",
        notInterested = "Not interested",
    ),
    komf = KomfStrings(
        providerSettings = KomfProviderSettingsStrings(
            providerAniList = "AniList",
            providerBangumi = "Bangumi",
            providerBookWalker = "Bookwalker Global",
            providerComicVine = "ComicVine",
            providerHentag = "Hentag",
            providerKodansha = "Kodansha US",
            providerMal = "MyAnimeList",
            providerMangaBaka = "MangaBaka",
            providerMangaUpdates = "MangaUpdates",
            providerMangaDex = "MangaDex",
            providerNautiljon = "Nautiljon",
            providerYenPress = "YenPress",
            providerViz = "Viz",
            providerWebtoons = "Webtoons",
        )
    ),
    imageSettings = ImageSettingsStrings(
        upsamplingMode = "Upsampling mode",
        upsamplingModeNearest = "Nearest neighbour",
        upsamplingModeBilinear = "Bilinear",
        upsamplingModeMitchell = "Bicubic Mitchell",
        upsamplingModeCatmullRom = "Bicubic Catmull-Rom",
        downsamplingKernel = "Downsampling kernel",
        downsamplingKernelNearest = "Nearest neighbour",
        downsamplingKernelLinear = "Linear",
        downsamplingKernelCubic = "Cubic",
        downsamplingKernelMitchell = "Mitchell",
        downsamplingKernelLanczos2 = "Lanczos2",
        downsamplingKernelLanczos3 = "Lanczos3",
        downsamplingKernelMKS2013 = "Magic Kernel Sharp 2013",
        downsamplingKernelMKS2021 = "Magic Kernel Sharp 2021",
        downsamplingKernelDefault = "Default",

        ncnnUpscaleMode = "NCNN upscale mode",
        ncnnUpscaleModeNone = "Disabled",
        ncnnUpscaleModeWaifu2x = "Waifu2x (Anime)",
        ncnnUpscaleModeRealCugan = "RealCUGAN (Conservative)",
        ncnnUpscaleModeRealSr = "RealSR (General)",
        ncnnUpscaleModeRealEsrgan = "Real-ESRGAN (Anime High-res)",
        ncnnUpscaleOnLoad = "Upscale on load",
        ncnnUpscaleOnLoadThreshold = "Min width threshold (px)",
        ncnnUpscaleOnLoadTooltip = "Trigger upscaling immediately when a page is opened if its width is smaller than the threshold.",

        onnxRuntimeExecutionProvider = "Onnx Runtime execution provider",
        onnxRuntimeUpscaleMode = "Onnx Runtime upscale mode",
        onnxRuntimeUpscaleModeNone = "Disabled",
        onnxRuntimeUpscaleModeUserModel = "User specified model",
        onnxRuntimeUpscaleModeMangaJaNai = "MangaJaNai preset"
        ),
        )