package snd.komelia.ui.strings

/**
 * French mirror of [EnStrings].
 *
 * Same shape, value for value: [AppStrings] is a data class, so a forgotten
 * field is a compile error rather than an English word left in the middle of a
 * French screen.
 *
 * Provider names (AniList, MangaDex…), technical mode names (Waifu2x, Lanczos3)
 * and the server's own vocabulary are deliberately left untranslated — they are
 * proper nouns, and translating them would break the match with the server's
 * own UI.
 */
val FrStrings = AppStrings(
    filters = FilterStrings(
        anyValue = "Tous",

        filterTagsSearch = "Rechercher un tag",
        filterTagsReset = "Réinitialiser",
        filterTagsGenreLabel = "Genre",
        filterTagsTagsLabel = "Tags",
        filterTagsShowMore = "Afficher plus",
        filterTagsShowLess = "Afficher moins",
        includeIfAllMatch = "Si tous correspondent",
        includeIfAnyMatch = "Si au moins un correspond",
        excludeIfAllMatch = "Si tous correspondent",
        excludeIfAnyMatch = "Si au moins un correspond",
    ),
    seriesFilter = SeriesFilterStrings(
        resetFilters = "Réinitialiser les filtres",
        hideFilters = "Masquer les filtres",
        anyValue = "Tous",
        search = "Rechercher",

        sort = "Trier par",
        sortRandom = "Aléatoire",
        sortRatingDesc = "Votre note",
        sortTitleAsc = "Titre croissant",
        sortTitleDesc = "Titre décroissant",
        sortDateAddedAsc = "Ajouts les plus anciens",
        sortDateAddedDesc = "Ajouts récents",
        sortReleaseDateAsc = "Parution la plus ancienne",
        sortReleaseDateDesc = "Parution la plus récente",
        sortUpdatedAsc = "Mise à jour la plus ancienne",
        sortUpdatedDesc = "Mise à jour la plus récente",
        sortFolderNameAsc = "Nom de dossier croissant",
        sortFolderNameDesc = "Nom de dossier décroissant",
        sortBooksCountAsc = "Moins de tomes",
        sortBooksCountDesc = "Plus de tomes",

        filterTagsLabel = "Filtrer les tags",
        readStatus = "Statut de lecture",
        readStatusUnread = "Non lu",
        readStatusInProgress = "En cours",
        readStatusRead = "Lu",

        publicationStatus = "Statut de publication",
        pubStatusEnded = "Terminée",
        pubStatusOngoing = "En cours",
        pubStatusAbandoned = "Abandonnée",
        pubStatusHiatus = "En pause",

        complete = "Complète",
        oneshot = "One-shot",
        authors = "Auteurs",
        publisher = "Éditeur",
        language = "Langue",
        releaseDate = "Date de parution",
        ageRating = "Âge conseillé"
    ),
    booksFilter = BookFilterStrings(
        sort = "Ordre de tri",
        sortNumberAsc = "Croissant",
        sortNumberDesc = "Décroissant",

        sortFileNameAsc = "Nom de fichier croissant",
        sortFileNameDesc = "Nom de fichier décroissant",
        sortReleaseDateAsc = "Parution la plus récente",
        sortReleaseDateDesc = "Parution la plus ancienne",

        readStatus = "Statut de lecture",
        readStatusUnread = "Non lu",
        readStatusInProgress = "En cours",
        readStatusRead = "Lu",

        authors = "Auteurs",
        tags = "Filtrer les tags",
    ),
    seriesView = SeriesViewStrings(
        statusEnded = "Terminée",
        statusOngoing = "En cours",
        statusAbandoned = "Abandonnée",
        statusHiatus = "En pause",
        readingDirectionLeftToRight = "De gauche à droite",
        readingDirectionRightToLeft = "De droite à gauche",
        readingDirectionVertical = "Verticale",
        readingDirectionWebtoon = "Webtoon",
    ),
    seriesEdit = SeriesEditStrings(
        title = "Titre",
        sortTitle = "Titre de tri",
        summary = "Résumé",
        language = "Langue",

        status = "Statut",
        statusEnded = "Terminée",
        statusOngoing = "En cours",
        statusAbandoned = "Abandonnée",
        statusHiatus = "En pause",

        readingDirection = "Sens de lecture",
        readingDirectionLeftToRight = "De gauche à droite",
        readingDirectionRightToLeft = "De droite à gauche",
        readingDirectionVertical = "Verticale",
        readingDirectionWebtoon = "Webtoon",
        publisher = "Éditeur",
        ageRating = "Âge conseillé",
        totalBookCount = "Nombre total de tomes"
    ),
    bookEdit = BookEditStrings(
        title = "Titre",
        number = "Numéro",
        sortNumber = "Numéro de tri",
        summary = "Résumé",
        releaseDate = "Date de parution",
        isbn = "ISBN"
    ),
    libraryEdit = LibraryEditStrings(
        emptyTrashAfterScan = "Vider la corbeille après chaque analyse",
        scanForceModifiedTime = "Forcer la date de modification des dossiers",
        scanOnStartup = "Analyser au démarrage",
        oneshotsDirectory = "Dossier des one-shots",
        excludeDirectories = "Dossiers exclus",

        scanInterval = "Intervalle d'analyse",
        scanIntervalDisabled = "Désactivé",
        scanIntervalHourly = "Toutes les heures",
        scanIntervalEvery6H = "Toutes les 6 heures",
        scanIntervalEvery12H = "Toutes les 12 heures",
        scanIntervalDaily = "Chaque jour",
        scanIntervalWeekly = "Chaque semaine",

        hashFiles = "Calculer l'empreinte des fichiers",
        hashPages = "Calculer l'empreinte des pages",
        analyzeDimensions = "Analyser les dimensions des pages",
        repairExtensions = "Corriger automatiquement les extensions incorrectes",
        convertToCbz = "Convertir automatiquement en CBZ",
        seriesCover = "Couverture de la série",
        coverFirst = "Premier tome",
        coverFirstUnreadOrFirst = "Premier non lu, sinon premier",
        coverFirstUnreadOrLast = "Premier non lu, sinon dernier",
        coverLast = "Dernier tome"
    ),
    userEdit = UserEditStrings(
        contentRestrictions = "Restrictions de contenu",
        age = "Âge",
        labelsAllow = "Autoriser uniquement ces labels",
        labelsExclude = "Exclure ces labels",
        ageRestriction = "Restrictions d'âge",
        ageRestrictionNone = "Aucune restriction",
        ageRestrictionAllowOnly = "Autoriser uniquement en dessous de",
        ageRestrictionExclude = "Exclure au-dessus de"
    ),
    reader = ReaderStrings(
        zoom = "Zoom",
        readerType = "Type de lecteur",
        readerPaged = "Page par page",
        readerPanels = "Cases",
        readerContinuous = "Continu",
        stretchToFit = "Agrandir les petites images",
        decoder = "Décodeur / échantillonneur d'image",
        pagesInfo = "Infos des pages",
        pageNumber = "page",
        memoryUsage = "Mémoire utilisée",
        pageDisplaySize = "taille affichée",
        pageOriginalSize = "taille d'origine",

        tapNavigation = "Navigation au toucher",
        modeLeftRight = "Par défaut",
        modeLeftRightDesc = "Gauche = page précédente · Droite = page suivante",
        modeRightLeft = "Inversée",
        modeRightLeftDesc = "Gauche = page suivante · Droite = page précédente",
        modeHorizontalSplit = "Haut / bas",
        modeHorizontalSplitDesc = "Moitié haute = page précédente · Moitié basse = page suivante",
        modeReversedHorizontalSplit = "Haut / bas inversé",
        modeReversedHorizontalSplitDesc = "Moitié haute = page suivante · Moitié basse = page précédente",
    ),
    pagedReader = PagedReaderStrings(
        scaleType = "Mise à l'échelle",
        scaleScreen = "Écran",
        scaleFitWidth = "Ajuster à la largeur",
        scaleFitHeight = "Ajuster à la hauteur",
        scaleOriginal = "Taille d'origine",
        readingDirection = "Sens de lecture",
        readingDirectionLeftToRight = "De gauche à droite",
        readingDirectionRightToLeft = "De droite à gauche",
        layout = "Disposition des pages",
        layoutSinglePage = "Page simple",
        layoutDoublePages = "Double page",
        layoutDoublePagesNoCover = "Double page (sans couverture)",
        offsetPages = "Décaler les pages",
        adaptiveBackground = "Fond adaptatif",
    ),
    continuousReader = ContinuousReaderStrings(
        sidePadding = "Marges latérales",
        pageSpacing = "Espacement des pages",
        readingDirection = "Sens de lecture",
        readingDirectionTopToBottom = "De haut en bas",
        readingDirectionLeftToRight = "De gauche à droite",
        readingDirectionRightToLeft = "De droite à gauche",
    ),
    settings = SettingsStrings(
        language = "Langue de l'interface",
        languageSystem = "Langue du système",
        serverSettings = "Paramètres du serveur",
        thumbnailSize = "Taille des vignettes",
        thumbnailSizeDefault = "Par défaut (300 px)",
        thumbnailSizeMedium = "Moyenne (600 px)",
        thumbnailSizeLarge = "Grande (900 px)",
        thumbnailSizeXLarge = "Très grande (1200 px)",

        thumbnailRegenTitle = "Regénérer les vignettes",
        thumbnailRegenBody = "La taille des vignettes a changé. Voulez-vous regénérer les vignettes des tomes ?",
        thumbnailRegenIfBigger = "OUI, MAIS SEULEMENT SI PLUS GRANDES",
        thumbnailRegenAllBooks = "OUI, TOUS LES TOMES",
        thumbnailRegenNo = "NON",

        deleteEmptyCollections = "Supprimer les collections vides après analyse",
        deleteEmptyReadLists = "Supprimer les listes de lecture vides après analyse",
        taskPoolSize = "Fils d'exécution des tâches",
        rememberMeDurationDays = "Durée du « Se souvenir de moi » (en jours)",
        renewRememberMeKey = "Regénérer la clé « Se souvenir de moi »",
        serverPort = "Port du serveur",
        serverContextPath = "URL de base",
        requiresRestart = "Nécessite un redémarrage pour prendre effet",
        serverSettingsDiscard = "Annuler",
        serverSettingsSave = "Enregistrer",

        appTheme = "Thème de l'application",
        appThemeDark = "Sombre",
        appThemeLight = "Clair",
        appThemeOled = "Très sombre",
        appThemeLightModern = "Clair moderne",
        appThemeDarkModern = "Sombre moderne",
        imageCardSize = "Taille des vignettes en grille (taille minimale d'affichage)",
        cardShadowLevel = "Intensité de l'ombre des cartes",
        cardCornerRadius = "Arrondi des coins des cartes",
        decoder = "Décodeur / échantillonneur d'image",
        epubReaderTypeKomga = "Lecteur EPUB Komga",
        epubReaderTypeTtsu = "Lecteur ッツ Ebook",
        epubReaderTypeEpub3 = "Lecteur EPUB3 (Android)",
    ),
    errorCodes = ErrorCodes(
        err1000 = "Le fichier n'a pas pu être lu pendant l'analyse",
        err1001 = "Type de média non pris en charge",
        err1002 = "Les archives RAR chiffrées ne sont pas prises en charge",
        err1003 = "Les archives RAR solides ne sont pas prises en charge",
        err1004 = "Les archives RAR multi-volumes ne sont pas prises en charge",
        err1005 = "Erreur inconnue pendant l'analyse du tome",
        err1006 = "Le tome ne contient aucune page",
        err1007 = "Certaines entrées n'ont pas pu être analysées",
        err1008 = "Erreur inconnue lors de la lecture des entrées du tome",
        err1009 = "Une liste de lecture porte déjà ce nom",
        err1015 = "Erreur lors de la lecture du fichier ComicRack CBL",
        err1016 = "Dossier inaccessible ou ce n'est pas un dossier",
        err1017 = "Impossible d'analyser un dossier appartenant à une bibliothèque existante",
        err1018 = "Fichier introuvable",
        err1019 = "Impossible d'importer un fichier appartenant à une bibliothèque existante",
        err1020 = "Le tome à mettre à niveau n'appartient pas à la série indiquée",
        err1021 = "Le fichier de destination existe déjà",
        err1022 = "Le tome importé n'a pas pu être analysé",
        err1023 = "Tome déjà présent dans la liste de lecture",
        err1024 = "Erreur de connexion OAuth2 : aucun attribut e-mail",
        err1025 = "Erreur de connexion OAuth2 : aucun compte local avec cet e-mail",
        err1026 = "Erreur de connexion OpenID Connect : e-mail non vérifié",
        err1027 = "Erreur de connexion OpenID Connect : aucun attribut email_verified",
        err1028 = "Erreur de connexion OpenID Connect : aucun attribut e-mail",
        err1029 = "Le fichier ComicRack CBL ne contient aucun élément Book",
        err1030 = "Le fichier ComicRack CBL n'a pas d'élément Name",
        err1031 = "Un élément Book du CBL n'a ni série ni numéro",
        err1032 = "Le fichier EPUB a un type de média incorrect",
        err1033 = "Certaines entrées sont manquantes",
        err1034 = "Une clé d'API porte déjà ce commentaire",
        err1035 = "Erreur lors de la lecture du sommaire EPUB",
        err1036 = "Erreur lors de la lecture des repères EPUB",
        err1037 = "Erreur lors de la lecture de la liste des pages EPUB",
        err1038 = "Erreur lors de la lecture des pages divina de l'EPUB",
        err1039 = "Erreur lors de la lecture des positions EPUB",
    ),
    ui = UiStrings(
        mapOf(
        // region generated-ui-strings
        "aCollectionWithThisName" to "Une collection porte déjà ce nom",
        "aReadListWithThis" to "Une liste de lecture porte déjà ce nom",
        "accentColorChipsTabs" to "Couleur d'accent (puces et onglets)",
        "accountSettings" to "Réglages du compte",
        "actions" to "Actions",
        "active" to "actif",
        "active2" to "Active",
        "add" to "Ajouter",
        "addANote" to "Ajouter une note…",
        "addBook" to "Ajouter un tome",
        "addCondition" to "Ajouter une condition",
        "addCustomRole" to "Ajouter un rôle personnalisé",
        "addField" to "Ajouter un champ",
        "addFilter" to "Ajouter un filtre",
        "addLink" to "Ajouter un lien",
        "addNewDiscordWebhook" to "Ajouter un webhook Discord",
        "addNote" to "Ajouter une note",
        "addOtherAddressesThatReach" to "Ajoutez d'autres adresses menant au MÊME serveur Komga (par exemple une IP locale à la maison et une adresse Tailscale à distance). Le profil est conservé : statistiques, notes et liens restent unifiés.",
        "addProvider" to "Ajouter un fournisseur",
        "addTerm" to "Ajouter un terme",
        "addToCollection" to "Ajouter à une collection",
        "addToReadList" to "Ajouter à une liste de lecture",
        "addUrl" to "Ajouter une URL",
        "addUrl2" to "Ajouter une URL",
        "addUser" to "Ajouter un utilisateur",
        "addWebhook" to "Ajouter un webhook",
        "addsADedicatedButtonTo" to "Ajoute un bouton dédié dans la barre de navigation pour ",
        "addsADedicatedStatsButton" to "Ajoute un bouton statistiques dans la barre de navigation ",
        "addsAGenreTabTo" to "Ajoute un onglet Genres à chaque bibliothèque, regroupant les séries par tags kora:genre:*. Nécessite une connexion au serveur.",
        "addsFeaturesAimedAtMetadata" to "Ajoute des fonctions de mise à jour et d'édition des métadonnées",
        "admin" to "Administration",
        "administrator" to "Administrateur",
        "age" to "Âge",
        "ageRating" to "Âge conseillé",
        "aggregate" to "Agréger",
        "aggregateAndCombineMetadataFrom" to "agrège les métadonnées de tous les fournisseurs actifs au lieu de garder le premier résultat",
        "aggregationSettings" to "Réglages d'agrégation",
        "align" to "Alignement",
        "all" to "Toutes",
        "all2" to "TOUT",
        "allLibraries" to "Toutes les bibliothèques",
        "alreadyContainsThisBook" to "contient déjà ce tome",
        "alreadyContainsThisSeries" to "contient déjà cette série",
        "alternateTitle" to "Titre alternatif",
        "alternateUrlsForThisServer" to "Autres adresses de ce serveur",
        "alternativeSeriesTitles" to "Titres alternatifs de la série",
        "alternativeTitleFallback" to "Titre alternatif de repli",
        "alternativeTitleLanguagesIso639" to "Langues des titres alternatifs (ISO 639)",
        "alternativeTitles" to "Autres titres",
        "alwaysShowProgressBarWhile" to "Toujours afficher la barre de progression pendant la lecture",
        "analyze" to "Analyser",
        "analyzeLibrary" to "Analyser la bibliothèque",
        "analyzeWithAnilist" to "Analyser avec AniList",
        "analyzing" to "Analyse en cours…",
        "anilistLinkSuggestionsOnline" to "Suggestions de liens AniList (en ligne)",
        "anilistSuggestions" to "Suggestions AniList",
        "announcements" to "Annonces",
        "annuler" to "Annuler",
        "apiForCrossPlatformEfficient" to " API multiplateforme d'accès au GPU, s'appuyant sur Vulkan, Metal ou Direct3D 12 selon le système",
        "appRestartIsRequiredFor" to "Un redémarrage de l'application est nécessaire",
        "appSettings" to "Réglages de l'application",
        "appUpdates" to "Mises à jour",
        "appearance" to "Apparence",
        "appendVolumeToSeriesTitle" to "Ajouter le tome au titre de la série",
        "appliedOnTheNextApp" to "Appliqué au prochain démarrage.",
        "appliesToBookAndSeries" to "S'applique aux pages tome et série. Désactivé = tous les rôles fournis par Komga",
        "applyAnyway" to "appliquer quand même",
        "applyBackup" to "Appliquer la sauvegarde ?",
        "appriseGithubPage" to "Page GitHub d'Apprise",
        "artistRoles" to "Rôles d'artiste",
        "attemptToOrderBooksUsing" to "Tente d'ordonner les tomes selon le motif de nommage du type de bibliothèque choisi",
        "aucunTagPRimTout" to "Aucun tag périmé. Tout est à jour.",
        "aucune" to "(aucune)",
        "aucuneSRieMasquE" to "Aucune série masquée. Appui long sur une série → « Masquer pour tous ».",
        "authenticationActivity" to "Activité de connexion",
        "author" to "Auteur",
        "authorRoles" to "Rôles d'auteur",
        "authors" to "Auteurs",
        "autoDetectDirectionUseSeries" to "Détecter le sens automatiquement (métadonnées de la série)",
        "autoDetectReadingDirection" to "Détecter le sens de lecture",
        "autoDetectWebtoon" to "Détecter les webtoons",
        "autoDetectWebtoonSwitchTo" to "Détecter les webtoons (bascule en défilement vertical)",
        "autoDownload" to "Automatic downloads",
        "autoDownloadBooksAhead" to "Volumes kept ready per series",
        "autoDownloadDescription" to "Off by default. Once on, the app keeps the next volumes of the series you are reading ready to read offline, within the limits below.",
        "autoDownloadExclude" to "Never download automatically",
        "autoDownloadLibrariesDescription" to "Leave empty to draw from every library.",
        "autoDownloadMaxSeries" to "Series followed",
        "autoDownloadOrder" to "Pinned series come first, then the ones you read most recently.",
        "autoDownloadPin" to "Always keep offline",
        "autoDownloadUnexclude" to "Allow automatic download",
        "autoDownloadUnpin" to "Stop keeping offline",
        "autoIdentify" to "Identification automatique",
        "autoIdentifyKomf" to "Identification automatique (Komf)",
        "autoSkipBlankPages" to "Ignorer les pages blanches",
        "automaticBackups" to "Sauvegardes automatiques",
        "automaticallyScanPagesForText" to "Analyser automatiquement le texte des pages",
        "back" to "Retour",
        "backToAuthors" to "Retour aux auteurs",
        "backToOnline" to "Repasser en ligne",
        "backToResults" to "Retour aux résultats",
        "backupFolder" to "Dossier de sauvegarde",
        "backupNow" to "Sauvegarder maintenant",
        "backupRestore" to "Sauvegarde et restauration",
        "backupRestore2" to "Sauvegarde et restauration",
        "betterTranslation" to "Meilleure traduction",
        "bibliothQuesDansToutes" to "Bibliothèques dans « Toutes »",
        "bibliothQuesInclusesDansToutes" to "Bibliothèques incluses dans « Toutes »",
        "biggerThanThisTheLists" to "Plus grand que ça — les listes ci-dessous contiennent tout.",
        "black" to "Noir",
        "blackBubbleWhiteTextArtwork" to "Bulle noire, texte blanc — le dessin n'est pas touché. Réduit l'éblouissement. Les bulles avec trame ou dégradé sont laissées telles quelles.",
        "blackBubbleWhiteTextArtwork2" to "Bulle noire, texte blanc — le dessin n'est pas touché. Réduit l'éblouissement. Les bulles avec trame ou dégradé sont laissées telles quelles. Également disponible dans les réglages du lecteur.",
        "body" to "Corps",
        "bookCount" to "Nombre de tomes",
        "bookCovers" to "Couvertures de tomes",
        "bookFilters" to "Filtres des tomes",
        "bookMetadata" to "Métadonnées du tome",
        "bookTitleExample" to "Exemple de titre de tome",
        "bookmarks" to "Marque-pages",
        "books" to "Tomes",
        "booksFinished" to "tomes terminés",
        "bottomMargin" to "Marge inférieure",
        "browse" to "Parcourir",
        "byDefaultBooksInA" to "Par défaut, les tomes d'une liste de lecture sont classés manuellement. Désactivez l'ordre manuel pour les trier par date de parution.",
        "byDefaultSeriesInA" to "Par défaut, les séries d'une collection sont classées par nom. Activez l'ordre manuel pour définir le vôtre.",
        "canBeSlowForHigh" to "peut être lent pour les images haute résolution",
        "cancel" to "Annuler",
        "cancel2" to "ANNULER",
        "cancelAllCurrentlyRunningTasks" to "Annuler toutes les tâches en cours",
        "cancelAllTasks" to "Annuler toutes les tâches",
        "cancelLoginAttempt" to "Annuler la tentative de connexion",
        "cardLayoutOverlayBackground" to "Fond du texte sur les fiches",
        "cards" to "Fiches",
        "category" to "Catégorie",
        "changeLocation" to "Changer d'emplacement",
        "changePassword" to "Changer le mot de passe",
        "channel" to "Canal",
        "chapterManagement" to "Chapter management",
        "chapterManagementAmbiguous" to "Several possible matches — pick one",
        "chapterManagementAmbiguousCount" to "to decide",
        "chapterManagementConfirmBulk" to "Each selected series with a single confident match will be linked to its volumes. Series with several possible matches are left for you to decide.",
        "chapterManagementDescription" to "Pairs series released chapter by chapter with the collected volumes they belong to. Admin only.",
        "chapterManagementEmpty" to "No chapter series here.",
        "chapterManagementErrors" to "Errors (also in the log file):",
        "chapterManagementFailedCount" to "failed",
        "chapterManagementFindMatch" to "Find match",
        "chapterManagementLinked" to "Linked to its volumes",
        "chapterManagementLinkedCount" to "linked",
        "chapterManagementLinkedOnly" to "Linked",
        "chapterManagementLocalOnly" to "Link sharing via Komga is off, or you are not an admin: the pairings made here stay on this device only. Turn it on in Settings -> Navigation.",
        "chapterManagementMatchSelected" to "Match selection",
        "chapterManagementNoMatch" to "No match found",
        "chapterManagementNoMatchCount" to "without a match",
        "chapterManagementReport" to "What happened",
        "chapterManagementUnlink" to "Unlink",
        "chapterManagementUnlinked" to "Not linked",
        "chapterManagementUnlinkedOnly" to "Unlinked",
        "chapters" to "Chapitres",
        "character" to "Personnage",
        "checkFoldersForNewOr" to "Cherche les tomes ajoutés ou retirés.\nSe base sur la date de modification des dossiers parents",
        "checkForUpdates" to "Vérifier les mises à jour",
        "checkForUpdatesOnStartup" to "Vérifier les mises à jour au démarrage",
        "choisirLaCouverture" to "Choisir la couverture",
        "choose" to "CHOISIR",
        "chooseAnImageDragAnd" to "Choisissez une image — glissez-déposez",
        "chooseLibrary" to "Choose a library",
        "chooseOnnxRuntimeVersion" to "Choisir la version d'ONNX Runtime",
        "chooseWhichAuthorRolesTo" to "Choisir les rôles d'auteur affichés",
        "cleanupIncludeManual" to "Also delete books downloaded by hand",
        "cleanupIncludeManualDescription" to "Off by default: a book you asked for yourself is never removed automatically.",
        "cleanupNow" to "Clean up now",
        "cleanupReadAfterDays" to "Delete books once read for",
        "cleanupReadAfterDaysDescription" to "Only books you finished are ever removed. A book you are part-way through stays.",
        "clear" to "Effacer",
        "clearAll" to "Tout effacer",
        "clearEpubCache" to "Vider le cache EPUB",
        "clearImageCache" to "Vider le cache des images",
        "clickOnItemsToSelect" to "Cliquez sur les éléments pour les sélectionner ou les désélectionner",
        "clickToSelectDragTo" to "Cliquez pour sélectionner, glissez pour changer l'ordre",
        "close" to "Fermer",
        "closeBook" to "Fermer le tome",
        "closeMenu" to "Fermer le menu",
        "collection" to "collection",
        "collection2" to "Collection",
        "collections" to "Collections",
        "colorCorrection" to "Correction des couleurs",
        "columns" to "Colonnes",
        "comicBookArchives" to "Archives de bandes dessinées",
        "comicvineClientId" to "Identifiant client ComicVine",
        "completed" to "Terminé",
        "computingSuggestions" to "Calcul des suggestions…",
        "condition" to "Condition",
        "confirm" to "Confirmer",
        "confirmerEtAppliquer" to "Confirmer et appliquer",
        "connectToANewServer" to "Se connecter à un nouveau serveur",
        "connected" to "Connecté",
        "connectedServers" to "Serveurs connectés",
        "connection" to "Connexion",
        "contentSettings" to "Content",
        "continueReading" to "Continuer la lecture",
        "continueReading2" to "Continuer la lecture",
        "continuous" to "Continu",
        "copiedToClipboard" to "Copié dans le presse-papiers",
        "copy" to "Copier",
        "copyStacktraceToClipboard" to "Copier la trace dans le presse-papiers",
        "corner" to "Anguleux",
        "couldNotComputeSuggestions" to "Impossible de calculer les suggestions.",
        "couldNotConnectToThe" to "Impossible de joindre le serveur. Voulez-vous passer en mode hors ligne ?",
        "cover" to "Couverture",
        "coverSettings" to "Réglages des couvertures",
        "crashLogs" to "Journaux de plantage",
        "create" to "Créer",
        "cropBorders" to "Rogner les bords",
        "cudaNvidiaGpusRequiresCuda12" to "CUDA (GPU Nvidia, nécessite CUDA12 et cuDNN9 installés)",
        "current" to "En cours :",
        "current2" to "Actuel",
        "currentVersion" to "Version actuelle :",
        "curves" to "Courbes",
        "customTileAppearance" to "Apparence personnalisée",
        "customUrl" to "URL personnalisée",
        "datasourceType" to "Type de source de données",
        "days" to "Jours",
        "deepScanAllLibraries" to "Analyse approfondie de toutes les bibliothèques",
        "default" to "Par défaut",
        "defaultSeriesLanguage" to "Langue par défaut des séries",
        "defaultSeriesReadingDirection" to "Sens de lecture par défaut des séries",
        "defaultValues" to "Valeurs par défaut",
        "delete" to "Supprimer",
        "deleteAll" to "Tout supprimer",
        "deleteAnnotation" to "Supprimer l'annotation",
        "deleteBook" to "Supprimer le tome",
        "deleteBookmark" to "Supprimer le marque-page",
        "deleteBooks" to "Supprimer les tomes",
        "deleteCollection" to "Supprimer la collection",
        "deleteDownloaded" to "Supprimer le téléchargement",
        "deleteDownloadedBook" to "Supprimer le tome téléchargé",
        "deleteDownloadedBooks" to "Supprimer les tomes téléchargés",
        "deleteDownloadedLibrary" to "Supprimer la bibliothèque téléchargée",
        "deleteDownloadedSeries" to "Supprimer les séries téléchargées",
        "deleteDownloadedSeries2" to "Supprimer la série téléchargée",
        "deleteFromServer" to "Supprimer du serveur",
        "deleteItemsMarkedAsUnavailable" to "Supprimer les éléments marqués indisponibles",
        "deleteLibrary" to "Supprimer la bibliothèque",
        "deletePreset" to "Supprimer le préréglage",
        "deleteReadList" to "Supprimer la liste de lecture",
        "deleteSavedSearch" to "Delete this saved search",
        "deleteSeries" to "Supprimer la série",
        "deleteSeries2" to "Supprimer la série",
        "deleteSeriesFromServer" to "Supprimer la série du serveur",
        "deleteServer" to "Supprimer le serveur",
        "deleteServerProfile" to "Supprimer le profil de serveur",
        "deleteUser" to "Supprimer l'utilisateur",
        "description" to "Description",
        "description4096CharactersMax" to "Description. 4096 caractères maximum",
        "diagnostics" to "Diagnostics",
        "direction" to "Sens",
        "directmlAnyGpu" to "DirectML (tout GPU)",
        "discard" to "Abandonner",
        "discordMarkdownText101" to "Le markdown Discord en bref",
        "dismiss" to "Ignorer",
        "display" to "Affichage",
        "displayTheBottomNavigationBar" to "Affiche la barre de navigation du bas sur les écrans série, tome et one-shot",
        "displayedNameEmptyDefault" to "Nom affiché (vide = par défaut)",
        "done" to "Terminé",
        "download" to "Télécharger",
        "downloadComplete" to "Téléchargement terminé ",
        "downloadCuda12" to "télécharger CUDA12",
        "downloadCudnn9" to "télécharger cuDNN9",
        "downloadModel" to "Télécharger le modèle",
        "downloadModel2" to "Télécharger le modèle",
        "downloadModels" to "Télécharger les modèles",
        "downloadOnnxRuntime" to "Télécharger ONNX Runtime",
        "downloadPolicy" to "Download policy",
        "downloadStorageLimit" to "Storage limit",
        "downloadStorageLimitDescription" to "When the limit is reached, finished books are removed oldest first. Downloads you start yourself are never blocked.",
        "downloadStorageUsed" to "Space used",
        "downloadTensorrt" to "télécharger TensorRT",
        "downloadWhileChargingOnly" to "Download only while charging",
        "downloadWhileChargingOnlyDescription" to "Downloads wait for the charger instead of being cancelled. Leave off if you download on battery.",
        "downloadWifiOnly" to "Download over Wi-Fi only",
        "downloadWifiOnlyDescription" to "Off by default. Left off, downloads use mobile data and a volume can weigh tens of megabytes.",
        "downloaded" to "Téléchargé",
        "downloading" to "Téléchargement…",
        "downloadingMangabakaDatabase" to "Téléchargement de la base MangaBaka",
        "downloadingOnnxRuntime" to "Téléchargement d'ONNX Runtime",
        "downloads" to "Téléchargements",
        "duplicateSeries" to "Duplicates",
        "duplicateSeriesClearIgnored" to "Restore ignored",
        "duplicateSeriesDescription" to "Series filed twice inside the same library. The scan reads the local index and sends no request to the server; only the Details button does, for one group at a time. Admin only.",
        "duplicateSeriesDetails" to "Details",
        "duplicateSeriesEmpty" to "No duplicate found.",
        "duplicateSeriesGroups" to "groups",
        "duplicateSeriesInvolved" to "series involved",
        "duplicateSeriesLanguageMissing" to "The index holds no language yet, so editions of one work still count as duplicates. Rebuild it from Maintenance.",
        "duplicateSeriesLikely" to "Duplicates",
        "duplicateSeriesNoLanguage" to "series have no language on the server, so two editions of one work can still be listed below.",
        "duplicateSeriesNoMatch" to "No group matches this filter.",
        "duplicateSeriesNotDuplicates" to "Not a duplicate",
        "duplicateSeriesNotIndexed" to "Not indexed, therefore not scanned:",
        "duplicateSeriesOpen" to "Open the series",
        "duplicateSeriesRescan" to "Scan again",
        "duplicateSeriesScanned" to "series scanned",
        "duplicateSeriesSearch" to "Filter by title",
        "duplicateSeriesShowMore" to "Show more",
        "duplicateSeriesUnsure" to "To check",
        "duplicateSeriesUnsureHint" to "Large groups sharing one title. Usually a collection name rather than the same work.",
        "edit" to "Modifier",
        "editModeClickToSelect" to "Mode édition : cliquez pour sélectionner, glissez pour changer l'ordre",
        "editUser" to "Modifier l'utilisateur",
        "email" to "E-mail",
        "emptyTrash" to "Vider la corbeille",
        "emptyTrashForAllLibraries" to "Vider la corbeille de toutes les bibliothèques",
        "emptyTrashForLibrary" to "Vider la corbeille de la bibliothèque",
        "enableAutomaticBackups" to "Activer les sauvegardes automatiques",
        "enableIgnoreList" to "Activer la liste d'exclusion",
        "enableKomfIntegration" to "Activer l'intégration Komf",
        "enableMetadataUpdateJobsFor" to "Activer la mise à jour des métadonnées pour ces bibliothèques",
        "enableNcnnUpscalerMobileOnly" to "Activer l'agrandissement NCNN (mobile uniquement)",
        "enableNotificationJobsForLibraries" to "Activer les notifications pour ces bibliothèques",
        "enableTextSelection" to "Activer la sélection de texte",
        "enabled" to "Activé",
        "engine" to "Moteur",
        "enterANameForThe" to "Nom du préréglage",
        "epub" to "EPUB",
        "epub3ReaderIsNotAvailable" to "Le lecteur EPUB3 n'est pas disponible sur cette plateforme.",
        "epubReader" to "Lecteur EPUB",
        "epubReaderSettings" to "Réglages du lecteur EPUB",
        "error" to "Erreur",
        "errorLoadingPage" to "This page could not be loaded",
        "errors" to "Erreurs",
        "eventListener" to "Écoute des événements",
        "exclusionMode" to "Mode exclusion",
        "exit" to "Quitter",
        "experimental" to "Expérimental",
        "export" to "Exporter…",
        "exportLogs" to "Exporter les journaux…",
        "failed" to "Échec",
        "failedToLoadMetadata" to "Échec du chargement des métadonnées",
        "failedToParseUrl" to "URL illisible",
        "favoris" to "Favoris",
        "favoris2" to "Favoris",
        "female" to "Femme",
        "fermer" to "Fermer",
        "fermer2" to "Fermer",
        "fieldName256CharactersMax" to "Nom du champ. 256 caractères maximum",
        "fieldValue1024CharactersMax" to "Valeur du champ. 1024 caractères maximum",
        "file" to "Fichier",
        "fileDownload" to "Téléchargement des fichiers",
        "filter" to "Filtrer",
        "filterExcluded" to "excluded",
        "filterLetter" to "Letter",
        "filterRating" to "Rating",
        "filterTag" to "Tag",
        "finishYourFirstBookTo" to "Terminez un premier tome pour voir des statistiques ici.",
        "finished" to "Terminé :",
        "flashDuration" to "Durée du flash",
        "flashEvery" to "Flash toutes les",
        "flashOnPageChange" to "Flash au changement de page",
        "flashWith" to "Flash en",
        "floatingNavBarKeepReading" to "Barre de navigation flottante, panneau « Continuer la lecture » et onglets en pastille",
        "floatingNavigationBar" to "Barre de navigation flottante",
        "fonctions" to "Fonctions",
        "font" to "Police",
        "fontGroupAccessible" to "Legibility",
        "fontGroupSerif" to "For reading",
        "fontGroupSystem" to "System",
        "fontGroupYours" to "Yours",
        "fontSize" to "Taille de police",
        "fontText" to "Police et texte",
        "footer2048CharactersMax" to "Pied de page. 2048 caractères maximum",
        "forYou" to "Pour vous",
        "forceTheScannerToCompare" to "Force l'analyseur à comparer tous les tomes analysés avec ceux de la base",
        "format" to "Format",
        "forward30Seconds" to "Avancer de 30 secondes",
        "frequency" to "Fréquence",
        "fullFeaturedWebClientFor" to "Client web complet pour Komga",
        "fuzzy" to "≈ Approximatif",
        "gRer" to "Gérer",
        "gamma" to "Gamma",
        "general" to "Général",
        "genre" to "Genre",
        "genreTab" to "Onglet Genres",
        "genreTileAppearance" to "Apparence des tuiles de genre",
        "genres" to "Genres",
        "genres2" to "Genres : ",
        "giveGenreTilesTheirOwn" to "Donne aux tuiles de genre leur propre taille et style de texte, au lieu de l'apparence globale des fiches.",
        "glossaryForThisSeries" to "Glossaire de cette série",
        "goBack" to "Retour",
        "goOffline" to "Passer hors ligne",
        "goOffline2" to "Passer hors ligne",
        "goOfflineAsCurrentUser" to "Passer hors ligne avec le compte actuel",
        "goOnline" to "Passer en ligne",
        "gotIt" to "Compris",
        "gridSize" to "Taille de la grille",
        "group" to "Groupe",
        "hideBooksFromTheseLibraries" to "Masquer les tomes de ces bibliothèques :",
        "hideChapterSeries" to "Hide chapter series (Chap)",
        "hideParenthesesInNames" to "Masquer les parenthèses dans les noms",
        "highPerformanceHardwareAcceleratedDirectx" to "Bibliothèque DirectX 12 accélérée matériellement pour l'apprentissage automatique",
        "highlight" to "Surligner",
        "highlightCompleteSeries" to "Mettre en avant les séries complètes",
        "home" to "Accueil",
        "identifyKomf" to "Identifier (Komf)",
        "ifAggregateOptionIsEnabled" to "si l'agrégation est active, fusionne les genres au lieu de garder ceux du premier résultat",
        "ifAggregateOptionIsEnabled2" to "si l'agrégation est active, fusionne les tags au lieu de garder ceux du premier résultat",
        "ifEntryAlreadyHasA" to "Si une couverture a déjà été envoyée, la nouvelle devient la couverture courante.\nSi désactivé, la couverture est envoyée sans être sélectionnée",
        "ifTheFirst3Pages" to "Si les 3 premières pages sont très hautes (hauteur ≥ 4× largeur), bascule en lecture case par case (zoom automatique sur chaque case). Votre choix manuel reste actif pour le reste de la session.",
        "ignoreList" to "Liste d'exclusion",
        "ignoredSeriesAndTheirBooks" to "Les séries exclues et leurs tomes sont masqués partout (bibliothèques, collections, recherche, accueil, genres). Local uniquement — jamais envoyé au serveur.",
        "image" to "Image",
        "imageReader" to "Lecteur d'images",
        "imageSettings" to "Réglages d'image",
        "immersiveCardColor" to "Couleur immersive des fiches",
        "import" to "Importer…",
        "importAnImage" to "Importer une image…",
        "importIsbnWithinBarcode" to "Importer l'ISBN du code-barres",
        "importLocalMediaAssets" to "Importer les ressources locales",
        "importMetadataForCbrCbz" to "Importer les métadonnées des CBR/CBZ contenant un fichier ComicInfo.xml",
        "importMetadataFromEpubFiles" to "Importer les métadonnées des fichiers EPUB",
        "importMetadataGeneratedByMylar" to "Importer les métadonnées générées par Mylar",
        "importSettings" to "Importer les réglages",
        "importerDesCouverturesDossier" to "Importer des couvertures (dossier)…",
        "inTheContinuousReaderA" to "En lecture continue, un appui franchit les gouttières d'un bloc et s'arrête sur les limites de case et de bulle, au lieu d'avancer de 80 % à l'aveugle. Revient à la distance fixe si la page ne peut pas être analysée. Également disponible dans les réglages du lecteur.",
        "includeLinks" to "Inclure les liens",
        "inclusionMode" to "Mode inclusion",
        "info" to "Infos",
        "inline" to "En ligne",
        "input" to "Entrée",
        "install" to "Installer",
        "installed" to "Installé",
        "invalidWebhookUrl" to "URL de webhook invalide",
        "invertSpeechBubbles" to "Inverser les bulles",
        "isbn" to "ISBN",
        "isbnBarcode" to "Code-barres ISBN",
        "jeton24CaractResMin" to "Jeton (24 caractères min)",
        "jobHistory" to "Historique des tâches",
        "kavitaApiKey" to "Clé d'API Kavita",
        "kavitaProcessing" to "Traitement Kavita",
        "kavitaUrl" to "URL Kavita",
        "keepScreenOnWhileReading" to "Garder l'écran allumé pendant la lecture",
        "key" to "Clé",
        "komfSeriesAutoIdentify" to "Identification automatique des séries par Komf",
        "komfSettings" to "Réglages Komf",
        "komfUrl" to "URL Komf",
        "komgaLogin" to "Connexion Komga",
        "komgaPassword" to "Mot de passe Komga",
        "komgaProcessing" to "Traitement Komga",
        "komgaToolkit" to "Boîte à outils Komga",
        "komgaUrl" to "URL Komga",
        "komgaUsername" to "Nom d'utilisateur Komga",
        "komgaWebui" to "Interface web Komga",
        "komgaWebuiEpubReaderAdapted" to "Lecteur EPUB de l'interface web Komga, adapté à Kora",
        "label" to "Libellé",
        "labels" to "Labels",
        "lancer" to "Lancer",
        "lancerEtAppliquer" to "Lancer et appliquer ?",
        "language" to "Langue",
        "lastRead" to "Dernière lecture :",
        "latestCheckedVersion" to "Dernière version vérifiée :",
        "launchProcessingJobsWhenNew" to "Lance les traitements à l'ajout d'une série ou d'un tome",
        "leave" to "Quitter",
        "levels" to "Niveaux",
        "libraries" to "Bibliothèques",
        "library" to "Bibliothèque",
        "librarySRootFolder" to "Dossier racine de la bibliothèque",
        "librarySwitcherInPageTitle" to "Sélecteur de bibliothèque dans le titre",
        "libraryTypeAffectsSomeOptions" to "Type de bibliothèque. Influence certaines options, surtout l'analyse des noms de tomes",
        "lifetime" to "Depuis toujours",
        "limit" to "Limite",
        "lineHeight" to "Interligne",
        "linearLightDownsampling" to "Réduction en lumière linéaire",
        "links" to "Liens",
        "lire" to "À lire",
        "lire2" to "À lire",
        "list" to "Liste",
        "listening" to "Écoute…",
        "loadFont" to "Charger une police…",
        "loadSmallPreviews" to "Charger de petits aperçus",
        "loadSmallPreviewsWhenDragging" to "Charger de petits aperçus pendant le déplacement du curseur",
        "localArtwork" to "Illustrations locales",
        "localDownloadOutdated" to "Téléchargement local obsolète",
        "lockScreenRotation" to "Verrouiller la rotation de l'écran",
        "logOut" to "Se déconnecter",
        "login" to "Se connecter",
        "login2" to "connexion",
        "loginWithAnotherAccount" to "Se connecter avec un autre compte",
        "logs" to "Journaux",
        "maintenance" to "Maintenance",
        "male" to "Homme",
        "manageConnectedServers" to "Gérer les serveurs connectés",
        "mangabakaOfflineDatabase" to "Base MangaBaka hors ligne",
        "mangajanaiOnnxModelsPreset" to "Préréglage de modèles ONNX MangaJaNai",
        "manualOrdering" to "Ordre manuel",
        "margins" to "Marges",
        "markAsRead" to "Marquer comme lu",
        "markAsUnread" to "Marquer comme non lu",
        "masquerPourTous" to "Masquer pour tous ?",
        "maximumLogSize" to "Taille maximale des journaux",
        "mediaManagement" to "Gestion des médias",
        "mediaType" to "Type de média",
        "median2000MsTheServer" to "Médiane ≥ 2000 ms : le goulot d'étranglement est le serveur, pas l'application.",
        "menu" to "Menu",
        "mergeAdjacentTextBlocksInto" to "Fusionne les blocs de texte voisins en un seul",
        "mergeGenres" to "Fusionner les genres",
        "mergeTags" to "Fusionner les tags",
        "mergeTextSegments" to "Fusionner les segments de texte",
        "metadata" to "Métadonnées",
        "metadataProvidersSettings" to "Réglages des fournisseurs de métadonnées",
        "metadataUpdateJobs" to "Tâches de mise à jour des métadonnées",
        "model" to "Modèle",
        "modelUrlSource" to "Source de l'URL du modèle",
        "modernTopAppBarAnd" to "Barre supérieure moderne et fiches revues",
        "more" to "Plus",
        "morphingCoverImageThatFlies" to "La couverture se transforme en vignette au déploiement",
        "morphingImmersiveCover" to "Couverture immersive animée",
        "myAccount" to "Mon compte",
        "myAuthenticationActivity" to "Mon activité de connexion",
        "myReadingStats" to "Mes statistiques de lecture",
        "myanimelistClientId" to "Identifiant client MyAnimeList",
        "name" to "Nom",
        "nameMatchingMode" to "Mode de correspondance des noms",
        "nativeEpub3ReaderWith" to "Lecteur EPUB 3 natif avec audio synchronisé (SMIL). Android uniquement.",
        "navigation" to "Navigation",
        "ncnnUpscalerLogs" to "Journaux NCNN / agrandissement",
        "never" to "Never",
        "newLibraryUi" to "Nouvelle interface de bibliothèque",
        "newPassword" to "Nouveau mot de passe",
        "newUi2" to "Nouvelle interface 2",
        "newVersionIsAvailable" to "Une nouvelle version est disponible",
        "next" to "Suivant",
        "next2" to "Suivant :",
        "nextChapter" to "Chapitre suivant",
        "nextPage" to "Page suivante",
        "nextSegment" to "Segment suivant",
        "nextVolume" to "Tome suivant",
        "nightMode" to "Night mode",
        "nightModeFrom" to "From",
        "nightModeIntensity" to "Warmth",
        "nightModeSchedule" to "Only during a time range",
        "nightModeTo" to "To",
        "nightModeWarmTintOnPages" to "Warms the pages to cut blue light. The menus are left alone.",
        "noAnnotationsYet" to "Aucune annotation pour l'instant",
        "noBookmarksYet" to "Aucun marque-page pour l'instant",
        "noBooks" to "Aucun tome",
        "noChaptersAvailable" to "Aucun chapitre disponible",
        "noGenresFoundInThis" to "Aucun genre dans cette bibliothèque. Ajoutez des tags kora:genre:* à vos séries dans Komga.",
        "noIgnoredSeriesLongPress" to "Aucune série exclue. Appui long sur une série puis « Exclure ».",
        "noLinksYetUseAdd" to "Aucun lien pour l'instant. Utilisez « Ajouter un lien » pour signaler d'autres versions (autre ",
        "noNextSeriesWithThe" to "Aucune série suivante avec les filtres actuels",
        "noReadingActivityYet" to "Aucune activité de lecture pour l'instant",
        "noResults" to "Aucun résultat",
        "noSavedSearches" to "No saved search yet",
        "noWorksFoundForThis" to "Aucune œuvre trouvée pour cet auteur",
        "nonDisponibleSurCettePlateforme" to "Non disponible sur cette plateforme.",
        "none" to "Aucun",
        "notDownloaded" to "Non téléchargé",
        "note" to "Note",
        "notes" to "Notes",
        "nothingToShow" to "Rien à afficher",
        "notificationContext" to "Contexte de la notification",
        "notificationSettings" to "Réglages des notifications",
        "notificationTemplate" to "Modèle de notification",
        "notifications" to "Notifications",
        "number" to "Numéro",
        "ocrEngine" to "Moteur OCR",
        "offline" to "Hors ligne",
        "offlineMode" to "Mode hors ligne",
        "offlineMode2" to "Mode hors ligne",
        "ok" to "OK",
        "oncePerLibrarySuggestionsAre" to "Une fois par bibliothèque. Les suggestions sont ensuite calculées sur l'appareil.",
        "onnxModelPath" to "Chemin du modèle ONNX",
        "onnxRuntimeSupportIsExperimental" to "La prise en charge d'ONNX Runtime est expérimentale.\nElle peut provoquer des plantages ou des instabilités",
        "onnxruntimeUpscaleMode" to "Mode d'agrandissement OnnxRuntime",
        "openInKomga" to "Ouvrir dans Komga",
        "openMenu" to "Ouvrir le menu",
        "openStats" to "Ouvrir les statistiques",
        "operator" to "Opérateur",
        "orderBooks" to "Ordonner les tomes",
        "originalSeries" to "Série d'origine",
        "otherOptions" to "Autres options",
        "otherTags" to "Autres tags",
        "otherwiseThePillSitsAt" to "Sinon la pastille reste en haut à gauche de la couverture",
        "otherwiseTheTitleIsOverlaid" to "Sinon le titre est superposé à la couverture.",
        "output" to "Sortie",
        "outputLevels" to "Niveaux de sortie",
        "ouvrirLeWebui" to "Ouvrir le WebUI",
        "overrideExistingCovers" to "Remplacer les couvertures existantes",
        "overrideExistingPreset" to "Remplacer le préréglage existant",
        "pRimTresBibliothQue" to "Périmètres (bibliothèque par catégorie)",
        "page" to "Page",
        "pageSpacing" to "Espacement des pages",
        "pageSpacing2" to "espacement des pages",
        "pageStreaming" to "Diffusion des pages",
        "paged" to "Page par page",
        "pages" to "pages",
        "pagesRead" to "Pages lues",
        "panelDetection" to "Détection des cases",
        "panels" to "Cases",
        "paraSpacing" to "Espacement des paragraphes",
        "parent" to "Parent",
        "parody" to "Parodie",
        "password" to "Mot de passe",
        "pauseAtTheLastPage" to "Marque une pause à la dernière page au lieu d'enchaîner silencieusement sur le tome suivant. Faites glisser à nouveau pour continuer. Garantit aussi que le tome en cours est marqué comme lu.",
        "pdf" to "PDF",
        "pendingTask" to "1 tâche en attente",
        "periodicallyWriteTheSameBackup" to "Écrit périodiquement le même fichier de sauvegarde dans un dossier de votre choix. ",
        "pickTheCorrectSeries" to "Choisissez la bonne série",
        "pillAtBottomLeft" to "Pastille en bas à gauche",
        "plusTard" to "Plus tard",
        "pointType" to "Type de point",
        "preferOriginalPublisherInsteadOf" to "Préfère l'éditeur d'origine à l'éditeur local",
        "presetWithThatNameAlready" to "Un préréglage porte déjà ce nom",
        "presets" to "Préréglages",
        "preventTheApplicationScreenFrom" to "Empêche l'écran de l'application de pivoter",
        "preventsGhostingOnEInk" to "Évite le maculage sur les écrans e-ink",
        "preview" to "Aperçu",
        "previous" to "Précédent",
        "previous2" to "Précédent :",
        "previousChapter" to "Chapitre précédent",
        "previousPage" to "Page précédente",
        "previousSegment" to "Segment précédent",
        "previousVolume" to "Tome précédent",
        "processing" to "Traitement…",
        "processing2" to "Traitement",
        "prochainesSorties" to "Prochaines sorties",
        "prochainesSorties2" to "Prochaines sorties",
        "projectLink" to "Lien du projet",
        "projectOnGithub" to "Le projet sur GitHub",
        "providers" to "Fournisseurs",
        "publisher" to "Éditeur",
        "publisherStyles" to "Styles de l'éditeur",
        "purgerLeTag" to "Purger le tag",
        "rAfficher" to "Restaurer",
        "rInitialiser" to "Réinitialiser",
        "randomSeriesInLibrary" to "Série au hasard dans la bibliothèque",
        "rapidocrModel" to "Modèle RapidOCR",
        "rapidocrModels" to "Modèles RapidOCR",
        "rate" to "Noter",
        "ratingAny" to "Any",
        "ratingAtLeast1" to "Rated",
        "ratingAtLeast3" to "3 stars and up",
        "ratingAtLeast4" to "4 stars and up",
        "ratingExactly5" to "5 stars",
        "reAnalyseAllLibraries" to "Re-analyse all libraries",
        "reAnalyseLibrary" to "Réanalyser la bibliothèque",
        "reDownloadModel" to "Retélécharger le modèle",
        "reDownloadModels" to "Retélécharger les modèles",
        "reachedTheStartOfThe" to "Début de la série atteint",
        "read" to "Lire",
        "readAloudHighlight" to "Surlignage de la lecture à voix haute",
        "readFromStart" to "Lire depuis le début",
        "readIncognito" to "Lire en incognito",
        "readIncognito2" to "Lire en incognito",
        "readList" to "liste de lecture",
        "readList2" to "Liste de lecture",
        "readLists" to "Listes de lecture",
        "readLists2" to "Listes de lecture",
        "readProgress" to "Progression :",
        "readProgressWillNotBe" to "La progression de lecture ne sera pas synchronisée",
        "readerSettings" to "Réglages du lecteur",
        "readerType" to "Type de lecteur",
        "reading" to "En cours de lecture",
        "readingMode" to "Mode de lecture",
        "readingMode2" to "Mode de lecture",
        "readingOrder" to "Ordre de lecture",
        "readingOrderEdition" to "edition",
        "readingOrderEditions" to "editions",
        "readingOrderMainLine" to "Main line",
        "readingOrderNoDeclaredOrder" to "No declared order",
        "readingOrderReadAfter" to "Read after",
        "readingOrderSameWorld" to "Same world",
        "readingOrderShowAll" to "Show all",
        "readingOrderShowLess" to "Show less",
        "readingOrderSpinOffs" to "Spin-offs",
        "readingOrderStartHere" to "Start here",
        "readingStats" to "Statistiques de lecture",
        "readsSharedSeriesRelationsFrom" to "Lit les relations de séries partagées depuis le serveur Komga (visibles pour ",
        "rebuildTheReadingOrder" to "Recalculer l'ordre de lecture",
        "recentDownloads" to "Téléchargements récents",
        "recentlyRead" to "Lus récemment",
        "recolorsTheTopRightBadge" to "Recolore le badge en haut à droite quand la série est terminée et que tous les tomes sont présents",
        "refresh" to "Actualiser",
        "refreshMetadata" to "Actualiser les métadonnées",
        "refreshMetadataForLibrary" to "Actualiser les métadonnées de la bibliothèque",
        "releaseDate" to "Date de parution",
        "releaseDate2" to "Date de parution",
        "releaseDate3" to "Date de parution :",
        "releaseNotes" to "Notes de version :",
        "reload" to "Recharger",
        "remoteUnavailable" to "Indisponible sur le serveur",
        "removeAnythingInParenthesesWhen" to "Retire ce qui est entre parenthèses dans les noms de séries et de one-shots",
        "removeComicinfoXml" to "Supprimer ComicInfo.xml ?",
        "removeFilter" to "Remove filter",
        "removeModel" to "Supprimer le modèle",
        "removeUrl" to "Retirer l'URL",
        "renameGenre" to "Renommer le genre",
        "renommer" to "Renommer",
        "repeatNewPassword" to "Confirmez le nouveau mot de passe",
        "replaceTheBottomNavigationBar" to "Remplace la barre de navigation du bas par une barre flottante",
        "requiresAddingThisHostAnd" to "Nécessite d'ajouter cet hôte et ce port à la configuration CORS de Komga",
        "requiresAppRestartToTake" to "Nécessite un redémarrage de l'application",
        "requiresWriteAccessToFiles" to "Nécessite un accès en écriture aux fichiers",
        "resetAll" to "Tout réinitialiser",
        "resetChannel" to "Réinitialiser le canal",
        "resetMetadataKomf" to "Réinitialiser les métadonnées (Komf)",
        "resetToDefault" to "Rétablir les valeurs par défaut",
        "resetToInternal" to "Revenir au stockage interne",
        "respectPublisherColors" to "Respecter les couleurs de l'éditeur",
        "restart" to "Redémarrer",
        "restore" to "Restaurer",
        "restoreAll" to "Tout restaurer",
        "retour" to "Retour",
        "retry" to "Réessayer",
        "returnBook" to "Retour au tome",
        "returnHome" to "Return home",
        "returnLibrary" to "Retour à la bibliothèque",
        "returnSerie" to "Retour à la série",
        "rewind10Seconds" to "Reculer de 10 secondes",
        "rienAppliquer" to "Rien à appliquer.",
        "rocmAmdGpusRequiresRocm7" to "ROCm (GPU AMD, nécessite ROCm7 installé)",
        "role" to "Rôle",
        "roles" to "Rôles",
        "roles2" to "Rôles :",
        "root" to "root",
        "rootFolder" to "Dossier racine",
        "runInBackground" to "Exécuter en arrière-plan",
        "running" to "En cours",
        "sRiesMasquEs" to "Séries masquées",
        "save" to "Enregistrer",
        "saveACopyOfYour" to "Enregistre une copie de vos réglages, filtres d'accueil, filtres de bibliothèque ",
        "saveChanges" to "Enregistrer les modifications",
        "saveImage" to "Enregistrer l'image",
        "savePreset" to "Enregistrer le préréglage",
        "saveSearch" to "Save search",
        "saveSearchName" to "Name of the search",
        "savedSearchReplaced" to "Replaces the search of the same name",
        "savedSearches" to "Saved searches",
        "savedSettings" to "Réglages enregistrés",
        "scanAllLibraries" to "Analyser toutes les bibliothèques",
        "scanForExistingFiles" to "Rechercher les fichiers existants",
        "scanForTheseFileTypes" to "Analyser ces types de fichiers",
        "scanLibraryFiles" to "Analyser les fichiers de la bibliothèque",
        "scanLibraryFilesDeep" to "Analyser les fichiers en profondeur",
        "scanText" to "Analyser le texte",
        "scroll" to "Défilement",
        "search" to "Rechercher",
        "searchASeriesByName" to "Rechercher une série par son nom",
        "searchAll" to "Tout rechercher…",
        "searchCollections" to "Rechercher des collections",
        "searchOrCreateCollection" to "Rechercher ou créer une collection",
        "searchOrCreateReadList" to "Rechercher ou créer une liste de lecture",
        "searchReadlists" to "Rechercher des listes de lecture",
        "searchResults" to "Résultats de recherche",
        "searchSeries" to "Rechercher une série",
        "searchSettings" to "Rechercher dans les réglages",
        "select" to "Sélectionner",
        "selectAll" to "Tout sélectionner",
        "selectText" to "Sélectionner le texte",
        "selected" to "Sélectionné",
        "selectionModeClickOnItems" to "Mode sélection : cliquez sur les éléments pour les sélectionner ou les désélectionner",
        "series" to "Séries",
        "seriesCovers" to "Couvertures de séries",
        "seriesMetadata" to "Métadonnées de la série",
        "seriesTitle" to "Titre de la série",
        "seriesTitleLanguageIso639" to "Langue du titre de série (ISO 639)",
        "server" to "Serveur",
        "serverManagement" to "Gestion du serveur",
        "serverSettings" to "Réglages du serveur",
        "serverUnavailable" to "Serveur indisponible",
        "serverUrl" to "URL du serveur",
        "serverUrlLoginAndReading" to "L'URL du serveur, les identifiants et la progression de lecture ne sont PAS inclus. ",
        "settings" to "Réglages",
        "shareLibraries" to "Partager des bibliothèques",
        "shareSeriesLinksViaKomga" to "Partager les liens de séries via Komga",
        "sharedOnServer" to "Partagé sur le serveur",
        "sharingLabel" to "Label de partage",
        "showASemiTransparentBackground" to "Affiche un fond semi-transparent derrière le texte des fiches",
        "showDateTime" to "Afficher la date et l'heure",
        "showFullPage" to "Afficher la page entière",
        "showLanguageOnCovers" to "Afficher la langue sur les couvertures",
        "showLocation" to "Afficher la position",
        "showNavigationBarInImmersive" to "Afficher la barre de navigation sur les écrans immersifs",
        "showSeriesCount" to "Afficher le nombre de séries",
        "showStatsInBottomNavigation" to "Afficher les statistiques dans la barre du bas",
        "showTheNumberOfSeries" to "Affiche le nombre de séries sous chaque genre.",
        "showTitleAndMetadataBelow" to "Affiche le titre et les métadonnées sous la vignette plutôt que dessus",
        "showUpcomingReleasesInBottom" to "Afficher les prochaines sorties dans la barre du bas",
        "showsAThumbnailWhileDragging" to "Affiche une vignette pendant le déplacement du curseur de navigation",
        "shutDownServer" to "Arrêter le serveur",
        "shutdown" to "Arrêter",
        "sidePadding" to "Marges latérales",
        "sidePadding2" to "marges latérales",
        "similar" to "Similaires",
        "sinceV1010" to "depuis la v1.0.10",
        "size" to "Taille",
        "slowerButPotentiallyMoreAccurate" to "plus lent, mais potentiellement plus fidèle",
        "smallFrEnPillOn" to "Petite pastille FR/EN sur les couvertures, seulement si la langue est connue",
        "smooth" to "Lissé",
        "sort" to "Tri",
        "sortNumber" to "Numéro de tri",
        "sorties" to "Sorties",
        "specialUserThatHasAccess" to "Utilisateur spécial ayant accès à tous les tomes téléchargés",
        "speechEngine" to "Moteur de reconnaissance vocale",
        "speechModelNotAvailableOn" to "Modèle vocal indisponible sur cet appareil.\nNécessite Android 12+ avec le modèle vocal Google.",
        "splitLandscapePages" to "Diviser les pages en paysage",
        "startupScreen" to "Écran de démarrage",
        "stats" to "Statistiques",
        "status" to "Statut",
        "stopAtEndOfBook" to "S'arrêter à la fin du tome (lecture continue)",
        "stopKomgaApplicationProcess" to "Arrêter le processus Komga",
        "storageLocation" to "Emplacement de stockage",
        "streak" to "Série en cours",
        "successful" to "Réussi",
        "suggestSameAuthorSimilarTitle" to "Suggérer (même auteur / titre proche)",
        "summary" to "Résumé",
        "switch" to "Basculer",
        "switchActiveUrl" to "Changer d'URL active",
        "switchLibrary" to "Changer de bibliothèque",
        "switchToThisServer" to "Basculer sur ce serveur",
        "tagScoreThreshold" to "Seuil de score des tags",
        "tagSizeLimit" to "Nombre maximal de tags",
        "tags" to "Tags",
        "tapToZoom" to "Toucher pour zoomer",
        "tappingInAVerticalStrip" to "Dans une bande verticale, un appui franchit les gouttières d'un bloc et s'arrête sur les limites de case et de bulle, au lieu d'une distance fixe.",
        "tensorrtNvidiaGpusRequiresCuda12" to "TensorRT (GPU Nvidia, nécessite CUDA12, cuDNN9 et TensorRT installés)",
        "term" to "Terme",
        "testSend" to "Envoi de test",
        "testTimeAugmentationSlowerBut" to "Test-Time Augmentation : plus lent, mais de meilleure qualité",
        "tester" to "Tester",
        "text" to "Texte",
        "textBelowCard" to "Texte sous la fiche",
        "textDetectionLanguage" to "Langue de détection du texte",
        "theSearchReturnedNoResults" to "La recherche n'a rien donné",
        "thereSNoNextBook" to "Il n'y a pas de tome suivant",
        "thereSNoPreviousBook" to "Il n'y a pas de tome précédent",
        "theseFeaturesAreExperimentalThey" to "Ces fonctions sont expérimentales — elles peuvent changer ou disparaître dans une prochaine version.",
        "thisMonth" to "Ce mois-ci",
        "thisWeek" to "Cette semaine",
        "thumbnail" to "Vignette",
        "tileSize" to "Taille des tuiles",
        "tintTheDetailCardBackground" to "Teinte le fond de la fiche avec la couleur dominante de la couverture",
        "title" to "Titre",
        "title256CharactersMax" to "Titre. 256 caractères maximum",
        "titleBelowCover" to "Titre sous la couverture",
        "titleSettings" to "Réglages des titres",
        "titleUrl" to "URL du titre",
        "toggleBookmark" to "Marque-page",
        "toggleTheme" to "Changer de thème",
        "topMargin" to "Marge supérieure",
        "total" to "Total",
        "toutPurger" to "Tout purger",
        "toutRAfficher" to "Tout restaurer",
        "toutes" to "Toutes",
        "toutes2" to "Toutes",
        "tracksBookCompletionsAndShows" to "Enregistre les tomes terminés et affiche vos habitudes de lecture ",
        "translate" to "Traduire",
        "translateFrom" to "Traduire depuis",
        "translation" to "Traduction",
        "trySearchingForSomethingElse" to "Essayez avec d'autres termes",
        "ttaMode" to "Mode TTA",
        "twoSequelsNoOrderBetween" to "Deux suites, sans ordre entre elles. Marquez l'une comme suite de l'autre pour les enchaîner.",
        "type" to "Type",
        "unavailable" to "Indisponible",
        "unknownSeries" to "Série inconnue",
        "unlinkSeries" to "Délier la série",
        "unset" to "Non défini",
        "update" to "Mettre à jour",
        "updateModes" to "Modes de mise à jour",
        "updateOnnxRuntime" to "Mettre à jour ONNX Runtime",
        "updateOrDownloadAnotherVersion" to "Mettre à jour ou télécharger une autre version d'ONNX Runtime",
        "updateSeriesAlternativeTitleIf" to "Met à jour les titres alternatifs si les métadonnées trouvées en contiennent",
        "updateSeriesTitleIfMatched" to "Met à jour le titre de la série si les métadonnées trouvées en contiennent un",
        "updates" to "Mises à jour",
        "updating" to "Mise à jour",
        "uploadBookCovers" to "Envoyer les couvertures de tomes",
        "uploadSeriesCover" to "Envoyer la couverture de la série",
        "uploadSeriesCovers" to "Envoyer les couvertures de séries",
        "upscalerSettings" to "Réglages de l'agrandissement",
        "upscaling" to "Agrandissement",
        "url" to "URL",
        "urlToolkitHttpHTe" to "URL Toolkit (http://hôte:port)",
        "urls" to "URL",
        "useFirstAvailableAlternativeTitle" to "Utilise le premier titre alternatif disponible si aucun titre principal dans la langue voulue n'est trouvé",
        "useOriginalPublisher" to "Utiliser l'éditeur d'origine",
        "useSeriesMetadataManualFlips" to "Utilise les métadonnées de la série. Les inversions manuelles sont mémorisées localement par série.",
        "userSettings" to "Réglages utilisateur",
        "username" to "Nom d'utilisateur",
        "users" to "Utilisateurs",
        "usesAppriseExecutableInstalledOn" to "Utilise l'exécutable Apprise installé sur le système.\nLes modèles sont rendus par Apache Velocity",
        "usesGoogleSOnDevice" to "Utilise le modèle embarqué de Google. Téléchargé automatiquement à la première utilisation.",
        "usesMarkdownSyntaxTemplatesAre" to "Utilise la syntaxe markdown. Les modèles sont rendus par Apache Velocity",
        "usesTensorrtToCreateOptimized" to "Utilise TensorRT pour créer un graphe optimisé. Le premier chargement du modèle est long ; ensuite le moteur est mis en cache",
        "value" to "Valeur",
        "velocityTemplateLanguageSyntaxReference" to "Référence de syntaxe Velocity Template Language",
        "viewLogs" to "Voir les journaux",
        "viewLogs2" to "Voir les journaux",
        "voiceSearch" to "Recherche vocale",
        "volumeKeysNavigation" to "Navigation avec les touches de volume",
        "webgpuAnyGpu" to "WebGPU (tout GPU)",
        "webhookUrl" to "URL du webhook",
        "webhooks" to "Webhooks",
        "webtoonSmartScroll" to "Défilement intelligent webtoon",
        "whatSNew" to "Nouveautés",
        "whenCropBordersIsOn" to "Quand « Rogner les bords » est actif, les pages blanches sont retirées du lecteur au lieu de le faire planter.",
        "whenOnTappingHomeLibrary" to "Quand c'est actif, toucher « Accueil » ou le nom de la bibliothèque en haut de ",
        "whichScreenKoraOpensTo" to "L'écran sur lequel Kora s'ouvre au lancement. ",
        "white" to "Blanc",
        "whiteAndBlack" to "Blanc et noir",
        "widgetProchainTome" to "Widget « Prochain tome »",
        "write" to "Écrire",
        "wrongSeriesSearchAnilist" to "Mauvaise série ? Chercher sur AniList",
        "youAreEditingAuthorsFor" to "Vous modifiez les auteurs de plusieurs tomes. Les auteurs actuels de chaque tome seront remplacés.",
        "youAreEditingTagsFor" to "Vous modifiez les tags de plusieurs séries. Les tags actuels de chaque série seront remplacés.",
        "youAreEditingTagsFor2" to "Vous modifiez les tags de plusieurs tomes. Les tags actuels de chaque tome seront remplacés.",
        "youHaveUnsavedChanges" to "Vous avez des modifications non enregistrées",
        "yourRating" to "Votre note",
        "yourReading" to "Vos lectures",
    // endregion
        "user" to "Utilisateur",
        "online" to "En ligne",
        "sharedLibraries" to "Bibliothèques partagées",
        "contentRestriction" to "Restriction de contenu",
        "sharing" to "Partage",
        "scanner" to "Scanner",
        "providerSettings" to "Réglages du fournisseur",
        "poster" to "Affiche",
        "options" to "Options",
        "alternateTitles" to "Titres alternatifs",
        "cardWidthGap" to "Écart en largeur",
        "cardHeightGap" to "Écart en hauteur",
        "cardSpacingBelow" to "Espace en dessous",
        "noBookFinishedThisMonth" to "Aucun livre terminé ce mois-ci",
        "oneBookThisMonth" to "1 livre ce mois-ci",
        "booksThisMonth" to "{n} livres ce mois-ci",
        "oneDayStreak" to "série de 1 jour",
        "dayStreak" to "série de {n} jours",
        )
    ),
    shelves = ShelfStrings(
        keepReading = "Reprendre la lecture",
        onDeck = "À enchaîner",
        recentlyReleasedBooks = "Tomes parus récemment",
        recentlyAddedBooks = "Tomes ajoutés récemment",
        recentlyAddedSeries = "Séries ajoutées récemment",
        recentlyUpdatedSeries = "Séries mises à jour récemment",
        recentlyReadBooks = "Tomes lus récemment",
        discover = "Découverte",
        forgotten = "Oubliés",
        almostFinished = "Presque terminées",
    ),
    editions = EditionStrings(
        heading = "Également disponible en",
        otherVersion = "Autre version",
        otherLanguage = "Autre langue",
        colourEdition = "Édition couleur",
        chapters = "Chapitres",
        volumes = "Volumes",
    ),
    roles = RoleStrings(
        writer = "Scénario",
        penciller = "Dessin",
        inker = "Encrage",
        colorist = "Couleurs",
        letterer = "Lettrage",
        cover = "Couverture",
        editor = "Édition",
        translator = "Traduction",
    ),
    shelfPatterns = ShelfPatternStrings(
        custom = "Personnalisée",
        onDeck = "À enchaîner",
        forgotten = "Oubliés",
        recentlyAdded = "Ajouts récents",
        recentlyUpdated = "Mises à jour récentes",
        almostFinished = "Presque terminées",
        favorites = "Favoris",
        series = "Séries",
        book = "Tomes",
        discover = "Découverte",
    ),
    counts = CountStrings(
        selected = { "$it sélectionné" + if (it > 1) "s" else "" },
        pages = { "$it page" + if (it > 1) "s" else "" },
        pagesLeft = { "$it page" + (if (it > 1) "s" else "") + " restante" + if (it > 1) "s" else "" },
        bookAndPages = { number, pages -> "Tome n°$number · $pages page" + if (pages > 1) "s" else "" },
        seriesCount = { "$it série" + if (it > 1) "s" else "" },
        booksCount = { "$it tome" + if (it > 1) "s" else "" },
        rolesFor = { "Rôles de $it" },
        inLibrary = { "dans $it" },
        releaseYear = { "Année de parution : $it" },
        processedFiles = { "$it fichier" + (if (it > 1) "s" else "") + " traité" + if (it > 1) "s" else "" },
    ),
    navigation = NavigationStrings(
        libraries = "Bibliothèques",
        home = "Accueil",
        search = "Rechercher",
        stats = "Statistiques",
        releases = "Sorties",
        settings = "Réglages",
    ),
    suggestions = SuggestionStrings(
        closestMatches = "Les plus proches",
        moreForYou = "Autres suggestions",
        becauseYouLiked = { "Parce que vous avez aimé $it" },
        becauseYouRead = { "Parce que vous avez lu $it" },
        becauseYouAreReading = { "Parce que vous lisez $it" },
        showRead = "Afficher les séries lues",
        buildingProfile = "Analyse de vos lectures…",
        analysingLibrary = { "Analyse de la bibliothèque… $it %" },
        failed = "Impossible de calculer les suggestions.",
        emptyNoProfile = "Rien sur quoi s'appuyer pour l'instant. Lisez ou notez quelques séries " +
            "de cette bibliothèque et les suggestions apparaîtront ici.",
        emptyAllRead = "Plus aucune suggestion. Essayez d'afficher les séries déjà lues.",
        profileSize = { "D'après $it séries que vous avez lues ou notées" },
        resetDismissed = { "Réinitialiser « pas intéressé » ($it)" },
        markPlanned = "Ajouter à « à lire »",
        unmarkPlanned = "Retirer de « à lire »",
        notInterested = "Pas intéressé",
    ),
    komf = KomfStrings(
        providerSettings = KomfProviderSettingsStrings(
            providerAniList = "AniList",
            providerBangumi = "Bangumi",
            providerBookWalker = "Bookwalker Global",
            providerComicVine = "ComicVine",
            providerHentag = "Hentag",
            providerKodansha = "Kodansha US",
            providerMal = "MyAnimeList",
            providerMangaBaka = "MangaBaka",
            providerMangaUpdates = "MangaUpdates",
            providerMangaDex = "MangaDex",
            providerNautiljon = "Nautiljon",
            providerYenPress = "YenPress",
            providerViz = "Viz",
            providerWebtoons = "Webtoons",
        )
    ),
    imageSettings = ImageSettingsStrings(
        upsamplingMode = "Mode d'agrandissement",
        upsamplingModeNearest = "Plus proche voisin",
        upsamplingModeBilinear = "Bilinéaire",
        upsamplingModeMitchell = "Bicubique Mitchell",
        upsamplingModeCatmullRom = "Bicubique Catmull-Rom",
        downsamplingKernel = "Noyau de réduction",
        downsamplingKernelNearest = "Plus proche voisin",
        downsamplingKernelLinear = "Linéaire",
        downsamplingKernelCubic = "Cubique",
        downsamplingKernelMitchell = "Mitchell",
        downsamplingKernelLanczos2 = "Lanczos2",
        downsamplingKernelLanczos3 = "Lanczos3",
        downsamplingKernelMKS2013 = "Magic Kernel Sharp 2013",
        downsamplingKernelMKS2021 = "Magic Kernel Sharp 2021",
        downsamplingKernelDefault = "Par défaut",

        ncnnUpscaleMode = "Mode d'agrandissement NCNN",
        ncnnUpscaleModeNone = "Désactivé",
        ncnnUpscaleModeWaifu2x = "Waifu2x (anime)",
        ncnnUpscaleModeRealCugan = "RealCUGAN (conservateur)",
        ncnnUpscaleModeRealSr = "RealSR (général)",
        ncnnUpscaleModeRealEsrgan = "Real-ESRGAN (anime haute résolution)",
        ncnnUpscaleOnLoad = "Agrandir au chargement",
        ncnnUpscaleOnLoadThreshold = "Largeur minimale (px)",
        ncnnUpscaleOnLoadTooltip = "Agrandit la page dès son ouverture si sa largeur est inférieure au seuil.",

        onnxRuntimeExecutionProvider = "Fournisseur d'exécution Onnx Runtime",
        onnxRuntimeUpscaleMode = "Mode d'agrandissement Onnx Runtime",
        onnxRuntimeUpscaleModeNone = "Désactivé",
        onnxRuntimeUpscaleModeUserModel = "Modèle personnalisé",
        onnxRuntimeUpscaleModeMangaJaNai = "Préréglage MangaJaNai"
    ),
)
